-- Generated by scripts/seed/generate.mjs. Do not edit by hand.
-- Local development data only.

begin;

insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, email_change,
  email_change_token_new, recovery_token)
values ('00000000-0000-0000-0000-000000000000', '00000000-0000-4000-8000-000000000001', 'authenticated', 'authenticated', 'admin@ciss.local',
  extensions.crypt('Admin12345!', extensions.gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}', '{"full_name":"CISS Admin"}'::jsonb, now(), now(), '', '', '', '')
on conflict (id) do nothing;
insert into auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
values (gen_random_uuid(), '00000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000000001', '{"sub":"00000000-0000-4000-8000-000000000001","email":"admin@ciss.local","email_verified":true}'::jsonb, 'email', now(), now(), now())
on conflict do nothing;
insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, email_change,
  email_change_token_new, recovery_token)
values ('00000000-0000-0000-0000-000000000000', '00000000-0000-4000-8000-000000000002', 'authenticated', 'authenticated', 'customer@ciss.local',
  extensions.crypt('Customer12345!', extensions.gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}', '{"full_name":"Wanjiku Kamau"}'::jsonb, now(), now(), '', '', '', '')
on conflict (id) do nothing;
insert into auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
values (gen_random_uuid(), '00000000-0000-4000-8000-000000000002', '00000000-0000-4000-8000-000000000002', '{"sub":"00000000-0000-4000-8000-000000000002","email":"customer@ciss.local","email_verified":true}'::jsonb, 'email', now(), now(), now())
on conflict do nothing;
insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, email_change,
  email_change_token_new, recovery_token)
values ('00000000-0000-0000-0000-000000000000', '00000000-0000-4000-8000-000000000003', 'authenticated', 'authenticated', 'brian@ciss.local',
  extensions.crypt('Customer12345!', extensions.gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}', '{"full_name":"Brian Otieno"}'::jsonb, now(), now(), '', '', '', '')
on conflict (id) do nothing;
insert into auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
values (gen_random_uuid(), '00000000-0000-4000-8000-000000000003', '00000000-0000-4000-8000-000000000003', '{"sub":"00000000-0000-4000-8000-000000000003","email":"brian@ciss.local","email_verified":true}'::jsonb, 'email', now(), now(), now())
on conflict do nothing;
insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, email_change,
  email_change_token_new, recovery_token)
values ('00000000-0000-0000-0000-000000000000', '00000000-0000-4000-8000-000000000004', 'authenticated', 'authenticated', 'amina@ciss.local',
  extensions.crypt('Customer12345!', extensions.gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}', '{"full_name":"Amina Hassan"}'::jsonb, now(), now(), '', '', '', '')
on conflict (id) do nothing;
insert into auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
values (gen_random_uuid(), '00000000-0000-4000-8000-000000000004', '00000000-0000-4000-8000-000000000004', '{"sub":"00000000-0000-4000-8000-000000000004","email":"amina@ciss.local","email_verified":true}'::jsonb, 'email', now(), now(), now())
on conflict do nothing;
update public.profiles set role = 'super_admin' where id = '00000000-0000-4000-8000-000000000001';
update public.profiles set role = 'customer' where id = '00000000-0000-4000-8000-000000000002';
update public.profiles set role = 'customer' where id = '00000000-0000-4000-8000-000000000003';
update public.profiles set role = 'customer' where id = '00000000-0000-4000-8000-000000000004';

insert into public.brands (name, slug, description, website, sort_order) values
  ('Epson', 'epson', 'Epson EcoTank printers, original ink bottles, scanners and genuine spare parts.', 'https://epson.co.ke', 0),
  ('HP', 'hp', 'HP LaserJet and ink printers, original toner cartridges and replacement parts.', 'https://www.hp.com', 10),
  ('Canon', 'canon', 'Canon PIXMA ink tank printers, imageCLASS lasers, scanners and ink.', 'https://www.canon-ea.com', 20),
  ('Brother', 'brother', 'Brother laser and ink tank printers, toner, drums and accessories.', 'https://www.brother.co.ke', 30),
  ('Samsung', 'samsung', 'Samsung laser printer toner and spare parts.', null, 40),
  ('Kyocera', 'kyocera', 'Kyocera ECOSYS printers and long-life toner kits.', 'https://www.kyoceradocumentsolutions.eu', 50),
  ('Xerox', 'xerox', 'Xerox printers, toner and drum cartridges.', null, 60),
  ('Ricoh', 'ricoh', 'Ricoh office printers, toner and maintenance parts.', null, 70),
  ('Konica Minolta', 'konica-minolta', 'Konica Minolta bizhub toner and imaging units.', null, 80),
  ('Pantum', 'pantum', 'Pantum affordable mono laser printers and toner.', null, 90);

insert into public.categories (name, slug, parent_id, description, image_url, sort_order, seo_title, seo_description)
values ('Printers', 'printers', null,
  'Ink tank, laser, dot matrix and photo printers for home, office and business in Kenya.', '/images/products/printer-inktank-black.svg', 0, 'Printers in Kenya | CISS Solutions', 'Ink tank, laser, dot matrix and photo printers for home, office and business in Kenya.');
insert into public.categories (name, slug, parent_id, description, image_url, sort_order, seo_title, seo_description)
values ('Ink Tank Printers', 'ink-tank', (select id from public.categories where slug = 'printers'),
  'High-yield ink tank printers with refillable bottles for the lowest cost per page.', '/images/products/printer-inktank-white.svg', 10, 'Ink Tank Printers in Kenya | CISS Solutions', 'High-yield ink tank printers with refillable bottles for the lowest cost per page.');
insert into public.categories (name, slug, parent_id, description, image_url, sort_order, seo_title, seo_description)
values ('Laser Printers', 'laser', (select id from public.categories where slug = 'printers'),
  'Fast, reliable mono and colour laser printers for offices.', '/images/products/printer-laser-white.svg', 20, 'Laser Printers in Kenya | CISS Solutions', 'Fast, reliable mono and colour laser printers for offices.');
insert into public.categories (name, slug, parent_id, description, image_url, sort_order, seo_title, seo_description)
values ('Dot Matrix Printers', 'dot-matrix', (select id from public.categories where slug = 'printers'),
  'Impact printers for invoices, multipart forms and receipts.', '/images/products/printer-dot-matrix.svg', 30, 'Dot Matrix Printers in Kenya | CISS Solutions', 'Impact printers for invoices, multipart forms and receipts.');
insert into public.categories (name, slug, parent_id, description, image_url, sort_order, seo_title, seo_description)
values ('Photo Printers', 'photo-printers', (select id from public.categories where slug = 'printers'),
  'Six-colour photo printers for studios and creatives.', '/images/products/printer-photo.svg', 40, 'Photo Printers in Kenya | CISS Solutions', 'Six-colour photo printers for studios and creatives.');
insert into public.categories (name, slug, parent_id, description, image_url, sort_order, seo_title, seo_description)
values ('Ink & Toner', 'ink-toner', null,
  'Original ink bottles, toner cartridges and drum units.', '/images/products/ink-bottle-set.svg', 50, 'Ink & Toner in Kenya | CISS Solutions', 'Original ink bottles, toner cartridges and drum units.');
insert into public.categories (name, slug, parent_id, description, image_url, sort_order, seo_title, seo_description)
values ('Ink', 'ink', (select id from public.categories where slug = 'ink-toner'),
  'Original refill ink bottles for ink tank printers.', '/images/products/ink-bottle-set.svg', 60, 'Ink in Kenya | CISS Solutions', 'Original refill ink bottles for ink tank printers.');
insert into public.categories (name, slug, parent_id, description, image_url, sort_order, seo_title, seo_description)
values ('Toner', 'toner', (select id from public.categories where slug = 'ink-toner'),
  'Toner cartridges and drum units for laser printers.', '/images/products/toner-black.svg', 70, 'Toner in Kenya | CISS Solutions', 'Toner cartridges and drum units for laser printers.');
insert into public.categories (name, slug, parent_id, description, image_url, sort_order, seo_title, seo_description)
values ('Spare Parts', 'spare-parts', null,
  'Genuine and compatible printer spare parts: rollers, printheads, fusers and maintenance kits.', '/images/products/printhead.svg', 80, 'Spare Parts in Kenya | CISS Solutions', 'Genuine and compatible printer spare parts: rollers, printheads, fusers and maintenance kits.');
insert into public.categories (name, slug, parent_id, description, image_url, sort_order, seo_title, seo_description)
values ('Printheads', 'printheads', (select id from public.categories where slug = 'spare-parts'),
  'Replacement printheads for ink tank printers.', '/images/products/printhead.svg', 90, 'Printheads in Kenya | CISS Solutions', 'Replacement printheads for ink tank printers.');
insert into public.categories (name, slug, parent_id, description, image_url, sort_order, seo_title, seo_description)
values ('Pickup Rollers', 'pickup-rollers', (select id from public.categories where slug = 'spare-parts'),
  'Pickup, separation and feed rollers to fix paper jams and misfeeds.', '/images/products/pickup-roller.svg', 100, 'Pickup Rollers in Kenya | CISS Solutions', 'Pickup, separation and feed rollers to fix paper jams and misfeeds.');
insert into public.categories (name, slug, parent_id, description, image_url, sort_order, seo_title, seo_description)
values ('Fuser Units', 'fuser-units', (select id from public.categories where slug = 'spare-parts'),
  'Fuser assemblies for laser printers.', '/images/products/fuser-unit.svg', 110, 'Fuser Units in Kenya | CISS Solutions', 'Fuser assemblies for laser printers.');
insert into public.categories (name, slug, parent_id, description, image_url, sort_order, seo_title, seo_description)
values ('Maintenance Kits', 'maintenance-kits', (select id from public.categories where slug = 'spare-parts'),
  'Waste ink pads, maintenance boxes and service kits.', '/images/products/maintenance-kit.svg', 120, 'Maintenance Kits in Kenya | CISS Solutions', 'Waste ink pads, maintenance boxes and service kits.');
insert into public.categories (name, slug, parent_id, description, image_url, sort_order, seo_title, seo_description)
values ('Paper Feed Parts', 'paper-feed-parts', (select id from public.categories where slug = 'spare-parts'),
  'Feed rollers, trays and paper path parts.', '/images/products/pickup-roller.svg', 130, 'Paper Feed Parts in Kenya | CISS Solutions', 'Feed rollers, trays and paper path parts.');
insert into public.categories (name, slug, parent_id, description, image_url, sort_order, seo_title, seo_description)
values ('Scanners', 'scanners', null,
  'Flatbed and document scanners for home and office.', '/images/products/scanner.svg', 140, 'Scanners in Kenya | CISS Solutions', 'Flatbed and document scanners for home and office.');
insert into public.categories (name, slug, parent_id, description, image_url, sort_order, seo_title, seo_description)
values ('Paper & Media', 'paper-media', null,
  'Copy paper, photo paper and printing media.', '/images/products/paper-ream.svg', 150, 'Paper & Media in Kenya | CISS Solutions', 'Copy paper, photo paper and printing media.');
insert into public.categories (name, slug, parent_id, description, image_url, sort_order, seo_title, seo_description)
values ('Accessories', 'accessories', null,
  'Cables and printer accessories.', '/images/products/usb-cable.svg', 160, 'Accessories in Kenya | CISS Solutions', 'Cables and printer accessories.');
insert into public.categories (name, slug, parent_id, description, image_url, sort_order, seo_title, seo_description)
values ('Cables', 'cables', (select id from public.categories where slug = 'accessories'),
  'USB printer cables.', '/images/products/usb-cable.svg', 170, 'Cables in Kenya | CISS Solutions', 'USB printer cables.');

insert into public.printer_models (brand_id, name, model_number, slug) values
  ((select id from public.brands where slug = 'epson'), 'Epson EcoTank L3250', 'L3250', 'epson-ecotank-l3250'),
  ((select id from public.brands where slug = 'epson'), 'Epson EcoTank L3210', 'L3210', 'epson-ecotank-l3210'),
  ((select id from public.brands where slug = 'epson'), 'Epson EcoTank L3150', 'L3150', 'epson-ecotank-l3150'),
  ((select id from public.brands where slug = 'epson'), 'Epson EcoTank L3110', 'L3110', 'epson-ecotank-l3110'),
  ((select id from public.brands where slug = 'epson'), 'Epson EcoTank L5290', 'L5290', 'epson-ecotank-l5290'),
  ((select id from public.brands where slug = 'epson'), 'Epson L805', 'L805', 'epson-l805'),
  ((select id from public.brands where slug = 'epson'), 'Epson LQ-310', 'LQ-310', 'epson-lq-310'),
  ((select id from public.brands where slug = 'hp'), 'HP LaserJet Pro M404dn', 'M404dn', 'hp-laserjet-pro-m404dn'),
  ((select id from public.brands where slug = 'hp'), 'HP LaserJet Pro M404dw', 'M404dw', 'hp-laserjet-pro-m404dw'),
  ((select id from public.brands where slug = 'hp'), 'HP LaserJet Pro M405dn', 'M405dn', 'hp-laserjet-pro-m405dn'),
  ((select id from public.brands where slug = 'hp'), 'HP LaserJet Pro M203dw', 'M203dw', 'hp-laserjet-pro-m203dw'),
  ((select id from public.brands where slug = 'hp'), 'HP LaserJet Pro MFP M227fdw', 'M227fdw', 'hp-laserjet-pro-mfp-m227fdw'),
  ((select id from public.brands where slug = 'canon'), 'Canon PIXMA G3420', 'G3420', 'canon-pixma-g3420'),
  ((select id from public.brands where slug = 'canon'), 'Canon PIXMA G2410', 'G2410', 'canon-pixma-g2410'),
  ((select id from public.brands where slug = 'canon'), 'Canon PIXMA G3411', 'G3411', 'canon-pixma-g3411'),
  ((select id from public.brands where slug = 'brother'), 'Brother HL-L2350DW', 'HL-L2350DW', 'brother-hl-l2350dw'),
  ((select id from public.brands where slug = 'brother'), 'Brother DCP-L2540DW', 'DCP-L2540DW', 'brother-dcp-l2540dw'),
  ((select id from public.brands where slug = 'brother'), 'Brother DCP-T420W', 'DCP-T420W', 'brother-dcp-t420w'),
  ((select id from public.brands where slug = 'brother'), 'Brother DCP-T520W', 'DCP-T520W', 'brother-dcp-t520w'),
  ((select id from public.brands where slug = 'kyocera'), 'Kyocera ECOSYS P2040dn', 'P2040dn', 'kyocera-ecosys-p2040dn'),
  ((select id from public.brands where slug = 'pantum'), 'Pantum P2500W', 'P2500W', 'pantum-p2500w');

insert into public.products (name, slug, sku, brand_id, category_id, printer_model_id, product_type,
  short_description, description, part_number, specifications, features, whats_included, warranty, price,
  compare_at_price, stock_quantity, low_stock_threshold, status, is_featured, is_bestseller, is_new, is_on_sale,
  seo_title, seo_description)
values ('Epson EcoTank L3250 All-in-One Wi-Fi Printer', 'epson-ecotank-l3250-all-in-one-printer', 'EPS-L3250',
  (select id from public.brands where slug = 'epson'),
  (select id from public.categories where slug = 'ink-tank'),
  (select id from public.printer_models where model_number = 'L3250'),
  'printer', 'Print • Scan • Copy • Wi-Fi', 'The Epson EcoTank L3250 is a compact, wireless all-in-one ink tank printer built for ultra-low printing costs. Its refillable tanks print up to 4,500 black and 7,500 colour pages from the included bottles, and Wi-Fi Direct lets you print straight from phones and laptops without a router. Ideal for homes, students and small offices that print often.', null, '[{"label":"Print Technology","value":"Heat-Free Micro Piezo inkjet (ink tank)"},{"label":"Functions","value":"Print, scan, copy"},{"label":"Print Speed","value":"Up to 10 ipm black / 5 ipm colour (ISO)"},{"label":"Resolution","value":"5760 × 1440 dpi"},{"label":"Connectivity","value":"Wi-Fi, Wi-Fi Direct, USB"},{"label":"Wi-Fi","value":"Yes"},{"label":"USB","value":"Hi-Speed USB 2.0"},{"label":"Duplex","value":"Manual"},{"label":"Paper Size","value":"A4, A5, A6, B5, Letter, Legal, envelopes"},{"label":"Monthly Duty Cycle","value":"Up to 3,000 pages"},{"label":"Dimensions","value":"375 × 347 × 179 mm"},{"label":"Weight","value":"3.9 kg"},{"label":"Warranty","value":"1 year or 30,000 pages"}]'::jsonb,
  array['Ultra-low cost printing with refillable ink tanks', 'Wireless and Wi-Fi Direct printing', 'Epson Smart Panel app for mobile printing and scanning', 'Spill-free, error-free bottle refilling', 'Borderless photo printing up to 4R']::text[], array['Epson EcoTank L3250 printer', '4 × Epson 003 ink bottles (BK, C, M, Y)', 'Power cable', 'Setup guide']::text[], '1 year or 30,000 pages',
  32999, 35000, 18, 3, 'active',
  true, true, false, false,
  'Epson EcoTank L3250 All-in-One Wi-Fi Printer Price in Kenya | CISS Solutions', 'Buy Epson EcoTank L3250 All-in-One Wi-Fi Printer in Kenya. Print • Scan • Copy • Wi-Fi. Genuine products, nationwide delivery and M-Pesa payment.');
insert into public.product_costs (product_id, cost_price)
values ((select id from public.products where sku = 'EPS-L3250'), 25739);
insert into public.product_images (product_id, url, alt_text, sort_order, is_primary)
values ((select id from public.products where sku = 'EPS-L3250'), '/images/products/printer-inktank-black.svg', 'Epson EcoTank L3250 All-in-One Wi-Fi Printer', 0, true);
insert into public.product_images (product_id, url, alt_text, sort_order, is_primary)
values ((select id from public.products where sku = 'EPS-L3250'), '/images/products/ink-bottle-set.svg', 'Epson EcoTank L3250 All-in-One Wi-Fi Printer – view 2', 1, false);

insert into public.products (name, slug, sku, brand_id, category_id, printer_model_id, product_type,
  short_description, description, part_number, specifications, features, whats_included, warranty, price,
  compare_at_price, stock_quantity, low_stock_threshold, status, is_featured, is_bestseller, is_new, is_on_sale,
  seo_title, seo_description)
values ('Epson EcoTank L3210 All-in-One Printer', 'epson-ecotank-l3210-all-in-one-printer', 'EPS-L3210',
  (select id from public.brands where slug = 'epson'),
  (select id from public.categories where slug = 'ink-tank'),
  (select id from public.printer_models where model_number = 'L3210'),
  'printer', 'Print • Scan • Copy • USB', 'A dependable USB ink tank all-in-one for high-volume home and office printing at a very low cost per page. Integrated tanks with bottle keys make refilling clean and simple.', null, '[{"label":"Print Technology","value":"Heat-Free Micro Piezo inkjet (ink tank)"},{"label":"Functions","value":"Print, scan, copy"},{"label":"Print Speed","value":"Up to 10 ipm black / 5 ipm colour (ISO)"},{"label":"Resolution","value":"5760 × 1440 dpi"},{"label":"Connectivity","value":"USB"},{"label":"Wi-Fi","value":"No"},{"label":"USB","value":"Hi-Speed USB 2.0"},{"label":"Duplex","value":"Manual"},{"label":"Paper Size","value":"A4, A5, A6, B5, Letter, Legal, envelopes"},{"label":"Monthly Duty Cycle","value":"Up to 3,000 pages"},{"label":"Dimensions","value":"375 × 347 × 179 mm"},{"label":"Weight","value":"3.9 kg"},{"label":"Warranty","value":"1 year"}]'::jsonb,
  array['Very low cost per page', 'Compact integrated tank design', 'Borderless printing up to 4R']::text[], array['Printer', '4 × Epson 003 ink bottles', 'USB cable', 'Power cable']::text[], '1 year',
  27499, null, 22, 3, 'active',
  false, true, false, false,
  'Epson EcoTank L3210 All-in-One Printer Price in Kenya | CISS Solutions', 'Buy Epson EcoTank L3210 All-in-One Printer in Kenya. Print • Scan • Copy • USB. Genuine products, nationwide delivery and M-Pesa payment.');
insert into public.product_costs (product_id, cost_price)
values ((select id from public.products where sku = 'EPS-L3210'), 21449);
insert into public.product_images (product_id, url, alt_text, sort_order, is_primary)
values ((select id from public.products where sku = 'EPS-L3210'), '/images/products/printer-inktank-white.svg', 'Epson EcoTank L3210 All-in-One Printer', 0, true);

insert into public.products (name, slug, sku, brand_id, category_id, printer_model_id, product_type,
  short_description, description, part_number, specifications, features, whats_included, warranty, price,
  compare_at_price, stock_quantity, low_stock_threshold, status, is_featured, is_bestseller, is_new, is_on_sale,
  seo_title, seo_description)
values ('Epson EcoTank L5290 Wi-Fi All-in-One with ADF', 'epson-ecotank-l5290-wifi-all-in-one-adf', 'EPS-L5290',
  (select id from public.brands where slug = 'epson'),
  (select id from public.categories where slug = 'ink-tank'),
  (select id from public.printer_models where model_number = 'L5290'),
  'printer', 'Print • Scan • Copy • Fax • ADF • Ethernet', 'Built for busy small offices: a 30-sheet automatic document feeder, fax, Ethernet and Wi-Fi, all with EcoTank running costs.', null, '[{"label":"Print Technology","value":"Heat-Free Micro Piezo inkjet (ink tank)"},{"label":"Functions","value":"Print, scan, copy, fax"},{"label":"Print Speed","value":"Up to 10 ipm black / 5 ipm colour (ISO)"},{"label":"Resolution","value":"5760 × 1440 dpi"},{"label":"Connectivity","value":"Wi-Fi, Wi-Fi Direct, Ethernet, USB"},{"label":"Wi-Fi","value":"Yes"},{"label":"USB","value":"Hi-Speed USB 2.0"},{"label":"Duplex","value":"Manual"},{"label":"Paper Size","value":"A4, A5, A6, B5, Letter, Legal, envelopes"},{"label":"Monthly Duty Cycle","value":"Up to 3,000 pages"},{"label":"Dimensions","value":"375 × 347 × 231 mm"},{"label":"Weight","value":"5.0 kg"},{"label":"Warranty","value":"1 year"}]'::jsonb,
  array['30-sheet ADF for multipage scanning and copying', 'Ethernet and Wi-Fi networking', 'Fax with PC-fax support']::text[], array['Printer', '4 × Epson 003 ink bottles', 'Power cable', 'Phone cable']::text[], '1 year',
  45999, 49500, 7, 3, 'active',
  true, false, false, true,
  'Epson EcoTank L5290 Wi-Fi All-in-One with ADF Price in Kenya | CISS Solutions', 'Buy Epson EcoTank L5290 Wi-Fi All-in-One with ADF in Kenya. Print • Scan • Copy • Fax • ADF • Ethernet. Genuine products, nationwide delivery and M-Pesa payment.');
insert into public.product_costs (product_id, cost_price)
values ((select id from public.products where sku = 'EPS-L5290'), 35879);
insert into public.product_images (product_id, url, alt_text, sort_order, is_primary)
values ((select id from public.products where sku = 'EPS-L5290'), '/images/products/printer-inktank-grey.svg', 'Epson EcoTank L5290 Wi-Fi All-in-One with ADF', 0, true);

insert into public.products (name, slug, sku, brand_id, category_id, printer_model_id, product_type,
  short_description, description, part_number, specifications, features, whats_included, warranty, price,
  compare_at_price, stock_quantity, low_stock_threshold, status, is_featured, is_bestseller, is_new, is_on_sale,
  seo_title, seo_description)
values ('Epson L805 Wi-Fi Photo Ink Tank Printer', 'epson-l805-wifi-photo-printer', 'EPS-L805',
  (select id from public.brands where slug = 'epson'),
  (select id from public.categories where slug = 'photo-printers'),
  (select id from public.printer_models where model_number = 'L805'),
  'printer', '6-colour photo • Wi-Fi • CD/DVD printing', 'Six-colour photo printing with lab-quality results, Wi-Fi and direct CD/DVD printing. A favourite of photo studios and creatives across Kenya.', null, '[{"label":"Print Technology","value":"6-colour inkjet (ink tank)"},{"label":"Functions","value":"Print"},{"label":"Print Speed","value":"Approx. 12 sec per 10 × 15 cm photo"},{"label":"Resolution","value":"5760 × 1440 dpi"},{"label":"Connectivity","value":"Wi-Fi, USB"},{"label":"Wi-Fi","value":"Yes"},{"label":"USB","value":"Hi-Speed USB 2.0"},{"label":"Duplex","value":"Manual"},{"label":"Paper Size","value":"A4, A5, A6, B5, Letter, Legal, envelopes"},{"label":"Dimensions","value":"542 × 289 × 169 mm"},{"label":"Weight","value":"6.0 kg"},{"label":"Warranty","value":"1 year"}]'::jsonb,
  array['Six-colour ink system for vivid photos', 'Print directly onto CD/DVDs', 'Borderless photos up to A4']::text[], array['Printer', '6 × ink bottles', 'CD/DVD tray', 'Power cable']::text[], '1 year',
  41500, null, 4, 3, 'active',
  false, false, false, false,
  'Epson L805 Wi-Fi Photo Ink Tank Printer Price in Kenya | CISS Solutions', 'Buy Epson L805 Wi-Fi Photo Ink Tank Printer in Kenya. 6-colour photo • Wi-Fi • CD/DVD printing. Genuine products, nationwide delivery and M-Pesa payment.');
insert into public.product_costs (product_id, cost_price)
values ((select id from public.products where sku = 'EPS-L805'), 32370);
insert into public.product_images (product_id, url, alt_text, sort_order, is_primary)
values ((select id from public.products where sku = 'EPS-L805'), '/images/products/printer-photo.svg', 'Epson L805 Wi-Fi Photo Ink Tank Printer', 0, true);

insert into public.products (name, slug, sku, brand_id, category_id, printer_model_id, product_type,
  short_description, description, part_number, specifications, features, whats_included, warranty, price,
  compare_at_price, stock_quantity, low_stock_threshold, status, is_featured, is_bestseller, is_new, is_on_sale,
  seo_title, seo_description)
values ('Canon PIXMA G3420 Wi-Fi Ink Tank All-in-One', 'canon-pixma-g3420-wifi-ink-tank', 'CAN-G3420',
  (select id from public.brands where slug = 'canon'),
  (select id from public.categories where slug = 'ink-tank'),
  (select id from public.printer_models where model_number = 'G3420'),
  'printer', 'Print • Scan • Copy • Wi-Fi', 'Canon''s wireless refillable ink tank printer with high page yields of up to 6,000 black and 7,000 colour pages per set of bottles.', null, '[{"label":"Print Technology","value":"Inkjet (refillable ink tank)"},{"label":"Functions","value":"Print, scan, copy"},{"label":"Print Speed","value":"Up to 9.1 ipm black / 5.0 ipm colour"},{"label":"Resolution","value":"4800 × 1200 dpi"},{"label":"Connectivity","value":"Wi-Fi, USB"},{"label":"Wi-Fi","value":"Yes"},{"label":"USB","value":"Hi-Speed USB 2.0"},{"label":"Duplex","value":"Manual"},{"label":"Paper Size","value":"A4, A5, A6, B5, Letter, Legal, envelopes"},{"label":"Dimensions","value":"445 × 330 × 163 mm"},{"label":"Weight","value":"6.3 kg"},{"label":"Warranty","value":"1 year"}]'::jsonb,
  array['High page yield GI-490 inks', 'Wireless printing from Canon PRINT app', 'Borderless photo printing']::text[], array['Printer', 'GI-490 ink bottles (BK, C, M, Y)', 'Print head set', 'Power cable']::text[], '1 year',
  25999, 27999, 15, 3, 'active',
  true, false, false, false,
  'Canon PIXMA G3420 Wi-Fi Ink Tank All-in-One Price in Kenya | CISS Solutions', 'Buy Canon PIXMA G3420 Wi-Fi Ink Tank All-in-One in Kenya. Print • Scan • Copy • Wi-Fi. Genuine products, nationwide delivery and M-Pesa payment.');
insert into public.product_costs (product_id, cost_price)
values ((select id from public.products where sku = 'CAN-G3420'), 20279);
insert into public.product_images (product_id, url, alt_text, sort_order, is_primary)
values ((select id from public.products where sku = 'CAN-G3420'), '/images/products/printer-inktank-black.svg', 'Canon PIXMA G3420 Wi-Fi Ink Tank All-in-One', 0, true);

insert into public.products (name, slug, sku, brand_id, category_id, printer_model_id, product_type,
  short_description, description, part_number, specifications, features, whats_included, warranty, price,
  compare_at_price, stock_quantity, low_stock_threshold, status, is_featured, is_bestseller, is_new, is_on_sale,
  seo_title, seo_description)
values ('Canon PIXMA G2410 Ink Tank All-in-One', 'canon-pixma-g2410-ink-tank', 'CAN-G2410',
  (select id from public.brands where slug = 'canon'),
  (select id from public.categories where slug = 'ink-tank'),
  (select id from public.printer_models where model_number = 'G2410'),
  'printer', 'Print • Scan • Copy • USB', 'An affordable refillable ink tank all-in-one for homes and students who want low running costs.', null, '[{"label":"Print Technology","value":"Inkjet (refillable ink tank)"},{"label":"Functions","value":"Print, scan, copy"},{"label":"Print Speed","value":"Up to 8.8 ipm black / 5.0 ipm colour"},{"label":"Resolution","value":"4800 × 1200 dpi"},{"label":"Connectivity","value":"USB"},{"label":"Wi-Fi","value":"No"},{"label":"USB","value":"Hi-Speed USB 2.0"},{"label":"Duplex","value":"Manual"},{"label":"Paper Size","value":"A4, A5, A6, B5, Letter, Legal, envelopes"},{"label":"Dimensions","value":"445 × 330 × 163 mm"},{"label":"Weight","value":"5.8 kg"},{"label":"Warranty","value":"1 year"}]'::jsonb,
  array['Low running costs', 'Integrated front-facing tanks', 'Borderless photos up to 4R']::text[], array['Printer', 'GI-490 ink bottles', 'Print head set', 'Power cable']::text[], '1 year',
  19999, null, 12, 3, 'active',
  false, false, true, false,
  'Canon PIXMA G2410 Ink Tank All-in-One Price in Kenya | CISS Solutions', 'Buy Canon PIXMA G2410 Ink Tank All-in-One in Kenya. Print • Scan • Copy • USB. Genuine products, nationwide delivery and M-Pesa payment.');
insert into public.product_costs (product_id, cost_price)
values ((select id from public.products where sku = 'CAN-G2410'), 15599);
insert into public.product_images (product_id, url, alt_text, sort_order, is_primary)
values ((select id from public.products where sku = 'CAN-G2410'), '/images/products/printer-inktank-white.svg', 'Canon PIXMA G2410 Ink Tank All-in-One', 0, true);

insert into public.products (name, slug, sku, brand_id, category_id, printer_model_id, product_type,
  short_description, description, part_number, specifications, features, whats_included, warranty, price,
  compare_at_price, stock_quantity, low_stock_threshold, status, is_featured, is_bestseller, is_new, is_on_sale,
  seo_title, seo_description)
values ('HP LaserJet Pro M404dn Mono Laser Printer', 'hp-laserjet-pro-m404dn', 'HP-M404DN',
  (select id from public.brands where slug = 'hp'),
  (select id from public.categories where slug = 'laser'),
  (select id from public.printer_models where model_number = 'M404dn'),
  'printer', '38 ppm • Duplex • Ethernet', 'Fast, secure mono laser printing for busy offices. Automatic two-sided printing, Gigabit Ethernet and HP Wolf security keep work moving.', null, '[{"label":"Print Technology","value":"Monochrome laser"},{"label":"Functions","value":"Print"},{"label":"Print Speed","value":"Up to 38 ppm (A4)"},{"label":"Resolution","value":"1200 × 1200 dpi"},{"label":"Connectivity","value":"Gigabit Ethernet, USB"},{"label":"Wi-Fi","value":"No"},{"label":"USB","value":"Hi-Speed USB 2.0"},{"label":"Duplex","value":"Automatic"},{"label":"Paper Size","value":"A4, A5, A6, B5, Letter, Legal, envelopes"},{"label":"Monthly Duty Cycle","value":"Up to 80,000 pages"},{"label":"Dimensions","value":"381 × 357 × 216 mm"},{"label":"Weight","value":"8.56 kg"},{"label":"Warranty","value":"1 year"}]'::jsonb,
  array['Automatic duplex printing', 'First page out in as fast as 6.3 seconds', '250-sheet input tray plus 100-sheet multipurpose tray']::text[], array['Printer', 'HP 59A starter toner cartridge', 'Power cable', 'Documentation']::text[], '1 year',
  52999, null, 9, 3, 'active',
  true, true, false, false,
  'HP LaserJet Pro M404dn Mono Laser Printer Price in Kenya | CISS Solutions', 'Buy HP LaserJet Pro M404dn Mono Laser Printer in Kenya. 38 ppm • Duplex • Ethernet. Genuine products, nationwide delivery and M-Pesa payment.');
insert into public.product_costs (product_id, cost_price)
values ((select id from public.products where sku = 'HP-M404DN'), 41339);
insert into public.product_images (product_id, url, alt_text, sort_order, is_primary)
values ((select id from public.products where sku = 'HP-M404DN'), '/images/products/printer-laser-white.svg', 'HP LaserJet Pro M404dn Mono Laser Printer', 0, true);
insert into public.product_images (product_id, url, alt_text, sort_order, is_primary)
values ((select id from public.products where sku = 'HP-M404DN'), '/images/products/toner-black.svg', 'HP LaserJet Pro M404dn Mono Laser Printer – view 2', 1, false);

insert into public.products (name, slug, sku, brand_id, category_id, printer_model_id, product_type,
  short_description, description, part_number, specifications, features, whats_included, warranty, price,
  compare_at_price, stock_quantity, low_stock_threshold, status, is_featured, is_bestseller, is_new, is_on_sale,
  seo_title, seo_description)
values ('HP LaserJet Pro M203dw Wireless Mono Laser', 'hp-laserjet-pro-m203dw', 'HP-M203DW',
  (select id from public.brands where slug = 'hp'),
  (select id from public.categories where slug = 'laser'),
  (select id from public.printer_models where model_number = 'M203dw'),
  'printer', '28 ppm • Duplex • Wi-Fi', 'Compact wireless laser printer with automatic duplex for small offices.', null, '[{"label":"Print Technology","value":"Monochrome laser"},{"label":"Functions","value":"Print"},{"label":"Print Speed","value":"Up to 28 ppm (A4)"},{"label":"Resolution","value":"1200 × 1200 dpi"},{"label":"Connectivity","value":"Wi-Fi, Ethernet, USB"},{"label":"Wi-Fi","value":"Yes"},{"label":"USB","value":"Hi-Speed USB 2.0"},{"label":"Duplex","value":"Automatic"},{"label":"Paper Size","value":"A4, A5, A6, B5, Letter, Legal, envelopes"},{"label":"Monthly Duty Cycle","value":"Up to 30,000 pages"},{"label":"Dimensions","value":"360 × 264 × 224 mm"},{"label":"Weight","value":"5.6 kg"},{"label":"Warranty","value":"1 year"}]'::jsonb,
  array['Wireless and mobile printing', 'Automatic duplex']::text[], array['Printer', 'HP 30A starter toner', 'Power cable']::text[], '1 year',
  34500, null, 0, 3, 'active',
  false, false, false, false,
  'HP LaserJet Pro M203dw Wireless Mono Laser Price in Kenya | CISS Solutions', 'Buy HP LaserJet Pro M203dw Wireless Mono Laser in Kenya. 28 ppm • Duplex • Wi-Fi. Genuine products, nationwide delivery and M-Pesa payment.');
insert into public.product_costs (product_id, cost_price)
values ((select id from public.products where sku = 'HP-M203DW'), 26910);
insert into public.product_images (product_id, url, alt_text, sort_order, is_primary)
values ((select id from public.products where sku = 'HP-M203DW'), '/images/products/printer-laser-dark.svg', 'HP LaserJet Pro M203dw Wireless Mono Laser', 0, true);

insert into public.products (name, slug, sku, brand_id, category_id, printer_model_id, product_type,
  short_description, description, part_number, specifications, features, whats_included, warranty, price,
  compare_at_price, stock_quantity, low_stock_threshold, status, is_featured, is_bestseller, is_new, is_on_sale,
  seo_title, seo_description)
values ('Brother HL-L2350DW Wireless Mono Laser Printer', 'brother-hl-l2350dw-wireless-laser', 'BRO-HLL2350DW',
  (select id from public.brands where slug = 'brother'),
  (select id from public.categories where slug = 'laser'),
  (select id from public.printer_models where model_number = 'HL-L2350DW'),
  'printer', '30 ppm • Duplex • Wi-Fi', 'Reliable compact mono laser with automatic two-sided printing and wireless connectivity. Uses separate toner and drum for lower running costs.', null, '[{"label":"Print Technology","value":"Monochrome laser"},{"label":"Functions","value":"Print"},{"label":"Print Speed","value":"Up to 30 ppm (A4)"},{"label":"Resolution","value":"2400 × 600 dpi"},{"label":"Connectivity","value":"Wi-Fi, Wi-Fi Direct, USB"},{"label":"Wi-Fi","value":"Yes"},{"label":"USB","value":"Hi-Speed USB 2.0"},{"label":"Duplex","value":"Automatic"},{"label":"Paper Size","value":"A4, A5, A6, B5, Letter, Legal, envelopes"},{"label":"Monthly Duty Cycle","value":"Up to 15,000 pages"},{"label":"Dimensions","value":"356 × 360 × 183 mm"},{"label":"Weight","value":"7.0 kg"},{"label":"Warranty","value":"1 year"}]'::jsonb,
  array['Separate toner and drum', 'Automatic duplex', 'Mobile printing']::text[], array['Printer', 'Inbox toner', 'Drum unit', 'Power cable']::text[], '1 year',
  28999, 31000, 11, 3, 'active',
  false, false, false, true,
  'Brother HL-L2350DW Wireless Mono Laser Printer Price in Kenya | CISS Solutions', 'Buy Brother HL-L2350DW Wireless Mono Laser Printer in Kenya. 30 ppm • Duplex • Wi-Fi. Genuine products, nationwide delivery and M-Pesa payment.');
insert into public.product_costs (product_id, cost_price)
values ((select id from public.products where sku = 'BRO-HLL2350DW'), 22619);
insert into public.product_images (product_id, url, alt_text, sort_order, is_primary)
values ((select id from public.products where sku = 'BRO-HLL2350DW'), '/images/products/printer-laser-dark.svg', 'Brother HL-L2350DW Wireless Mono Laser Printer', 0, true);

insert into public.products (name, slug, sku, brand_id, category_id, printer_model_id, product_type,
  short_description, description, part_number, specifications, features, whats_included, warranty, price,
  compare_at_price, stock_quantity, low_stock_threshold, status, is_featured, is_bestseller, is_new, is_on_sale,
  seo_title, seo_description)
values ('Brother DCP-T420W Wi-Fi Ink Tank All-in-One', 'brother-dcp-t420w-ink-tank', 'BRO-DCPT420W',
  (select id from public.brands where slug = 'brother'),
  (select id from public.categories where slug = 'ink-tank'),
  (select id from public.printer_models where model_number = 'DCP-T420W'),
  'printer', 'Print • Scan • Copy • Wi-Fi', 'Wireless refill ink tank printer with high-yield BTD60BK and BT5000 inks.', null, '[{"label":"Print Technology","value":"Inkjet (refill ink tank)"},{"label":"Functions","value":"Print, scan, copy"},{"label":"Print Speed","value":"Up to 16 ipm mono / 9 ipm colour"},{"label":"Resolution","value":"6000 × 1200 dpi"},{"label":"Connectivity","value":"Wi-Fi, USB"},{"label":"Wi-Fi","value":"Yes"},{"label":"USB","value":"Hi-Speed USB 2.0"},{"label":"Duplex","value":"Manual"},{"label":"Paper Size","value":"A4, A5, A6, B5, Letter, Legal, envelopes"},{"label":"Monthly Duty Cycle","value":"2,500 pages"},{"label":"Dimensions","value":"435 × 359 × 159 mm"},{"label":"Weight","value":"6.6 kg"},{"label":"Warranty","value":"1 year"}]'::jsonb,
  array['Up to 7,500 mono pages per bottle', 'Wireless printing']::text[], array['Printer', 'Starter ink bottles', 'Power cable']::text[], '1 year',
  26500, null, 6, 3, 'active',
  false, false, true, false,
  'Brother DCP-T420W Wi-Fi Ink Tank All-in-One Price in Kenya | CISS Solutions', 'Buy Brother DCP-T420W Wi-Fi Ink Tank All-in-One in Kenya. Print • Scan • Copy • Wi-Fi. Genuine products, nationwide delivery and M-Pesa payment.');
insert into public.product_costs (product_id, cost_price)
values ((select id from public.products where sku = 'BRO-DCPT420W'), 20670);
insert into public.product_images (product_id, url, alt_text, sort_order, is_primary)
values ((select id from public.products where sku = 'BRO-DCPT420W'), '/images/products/printer-inktank-grey.svg', 'Brother DCP-T420W Wi-Fi Ink Tank All-in-One', 0, true);

insert into public.products (name, slug, sku, brand_id, category_id, printer_model_id, product_type,
  short_description, description, part_number, specifications, features, whats_included, warranty, price,
  compare_at_price, stock_quantity, low_stock_threshold, status, is_featured, is_bestseller, is_new, is_on_sale,
  seo_title, seo_description)
values ('Pantum P2500W Wireless Mono Laser Printer', 'pantum-p2500w-wireless-laser', 'PAN-P2500W',
  (select id from public.brands where slug = 'pantum'),
  (select id from public.categories where slug = 'laser'),
  (select id from public.printer_models where model_number = 'P2500W'),
  'printer', '22 ppm • Wi-Fi • Compact', 'An affordable compact wireless laser printer, ideal for homes, cyber cafés and small offices.', null, '[{"label":"Print Technology","value":"Monochrome laser"},{"label":"Functions","value":"Print"},{"label":"Print Speed","value":"Up to 22 ppm (A4)"},{"label":"Resolution","value":"1200 × 1200 dpi"},{"label":"Connectivity","value":"Wi-Fi, USB"},{"label":"Wi-Fi","value":"Yes"},{"label":"USB","value":"Hi-Speed USB 2.0"},{"label":"Duplex","value":"Manual"},{"label":"Paper Size","value":"A4, A5, A6, B5, Letter, Legal, envelopes"},{"label":"Monthly Duty Cycle","value":"Up to 15,000 pages"},{"label":"Dimensions","value":"337 × 220 × 178 mm"},{"label":"Weight","value":"4.75 kg"},{"label":"Warranty","value":"1 year"}]'::jsonb,
  array['Very affordable laser printing', 'Wireless printing']::text[], array['Printer', 'Starter toner (1,600 pages)', 'Power cable']::text[], '1 year',
  15999, null, 25, 3, 'active',
  true, false, true, false,
  'Pantum P2500W Wireless Mono Laser Printer Price in Kenya | CISS Solutions', 'Buy Pantum P2500W Wireless Mono Laser Printer in Kenya. 22 ppm • Wi-Fi • Compact. Genuine products, nationwide delivery and M-Pesa payment.');
insert into public.product_costs (product_id, cost_price)
values ((select id from public.products where sku = 'PAN-P2500W'), 12479);
insert into public.product_images (product_id, url, alt_text, sort_order, is_primary)
values ((select id from public.products where sku = 'PAN-P2500W'), '/images/products/printer-laser-white.svg', 'Pantum P2500W Wireless Mono Laser Printer', 0, true);

insert into public.products (name, slug, sku, brand_id, category_id, printer_model_id, product_type,
  short_description, description, part_number, specifications, features, whats_included, warranty, price,
  compare_at_price, stock_quantity, low_stock_threshold, status, is_featured, is_bestseller, is_new, is_on_sale,
  seo_title, seo_description)
values ('Kyocera ECOSYS P2040dn Mono Laser Printer', 'kyocera-ecosys-p2040dn', 'KYO-P2040DN',
  (select id from public.brands where slug = 'kyocera'),
  (select id from public.categories where slug = 'laser'),
  (select id from public.printer_models where model_number = 'P2040dn'),
  'printer', '40 ppm • Duplex • Long-life drum', 'Kyocera''s long-life components deliver some of the lowest running costs in its class.', null, '[{"label":"Print Technology","value":"Monochrome laser"},{"label":"Functions","value":"Print"},{"label":"Print Speed","value":"Up to 40 ppm (A4)"},{"label":"Resolution","value":"1200 × 1200 dpi"},{"label":"Connectivity","value":"Gigabit Ethernet, USB"},{"label":"Wi-Fi","value":"No"},{"label":"USB","value":"Hi-Speed USB 2.0"},{"label":"Duplex","value":"Automatic"},{"label":"Paper Size","value":"A4, A5, A6, B5, Letter, Legal, envelopes"},{"label":"Monthly Duty Cycle","value":"Up to 50,000 pages"},{"label":"Dimensions","value":"375 × 393 × 272 mm"},{"label":"Weight","value":"11.5 kg"},{"label":"Warranty","value":"1 year"}]'::jsonb,
  array['Long-life drum', 'Automatic duplex']::text[], array['Printer', 'Starter toner', 'Power cable']::text[], '1 year',
  48000, null, 3, 3, 'active',
  false, false, false, false,
  'Kyocera ECOSYS P2040dn Mono Laser Printer Price in Kenya | CISS Solutions', 'Buy Kyocera ECOSYS P2040dn Mono Laser Printer in Kenya. 40 ppm • Duplex • Long-life drum. Genuine products, nationwide delivery and M-Pesa payment.');
insert into public.product_costs (product_id, cost_price)
values ((select id from public.products where sku = 'KYO-P2040DN'), 37440);
insert into public.product_images (product_id, url, alt_text, sort_order, is_primary)
values ((select id from public.products where sku = 'KYO-P2040DN'), '/images/products/printer-laser-white.svg', 'Kyocera ECOSYS P2040dn Mono Laser Printer', 0, true);

insert into public.products (name, slug, sku, brand_id, category_id, printer_model_id, product_type,
  short_description, description, part_number, specifications, features, whats_included, warranty, price,
  compare_at_price, stock_quantity, low_stock_threshold, status, is_featured, is_bestseller, is_new, is_on_sale,
  seo_title, seo_description)
values ('Epson LQ-310 24-pin Dot Matrix Printer', 'epson-lq-310-dot-matrix', 'EPS-LQ310',
  (select id from public.brands where slug = 'epson'),
  (select id from public.categories where slug = 'dot-matrix'),
  (select id from public.printer_models where model_number = 'LQ-310'),
  'printer', '24-pin • Multipart forms', 'A rugged 24-pin dot matrix printer for invoices, delivery notes and multipart forms.', null, '[{"label":"Print Technology","value":"24-pin impact dot matrix"},{"label":"Functions","value":"Print"},{"label":"Print Speed","value":"Up to 416 cps"},{"label":"Resolution","value":"360 × 180 dpi"},{"label":"Connectivity","value":"USB, parallel"},{"label":"Wi-Fi","value":"No"},{"label":"USB","value":"Hi-Speed USB 2.0"},{"label":"Duplex","value":"Manual"},{"label":"Paper Size","value":"Continuous, cut sheet, multipart (1 + 3 copies)"},{"label":"Dimensions","value":"348 × 275 × 159 mm"},{"label":"Weight","value":"4.1 kg"},{"label":"Warranty","value":"1 year"}]'::jsonb,
  array['Prints original + 3 copies', 'Low running cost ribbons']::text[], array['Printer', 'Ribbon cartridge', 'Power cable']::text[], '1 year',
  36999, null, 5, 3, 'active',
  false, false, false, false,
  'Epson LQ-310 24-pin Dot Matrix Printer Price in Kenya | CISS Solutions', 'Buy Epson LQ-310 24-pin Dot Matrix Printer in Kenya. 24-pin • Multipart forms. Genuine products, nationwide delivery and M-Pesa payment.');
insert into public.product_costs (product_id, cost_price)
values ((select id from public.products where sku = 'EPS-LQ310'), 28859);
insert into public.product_images (product_id, url, alt_text, sort_order, is_primary)
values ((select id from public.products where sku = 'EPS-LQ310'), '/images/products/printer-dot-matrix.svg', 'Epson LQ-310 24-pin Dot Matrix Printer', 0, true);

insert into public.products (name, slug, sku, brand_id, category_id, printer_model_id, product_type,
  short_description, description, part_number, specifications, features, whats_included, warranty, price,
  compare_at_price, stock_quantity, low_stock_threshold, status, is_featured, is_bestseller, is_new, is_on_sale,
  seo_title, seo_description)
values ('Epson 003 Original Ink Bottle (65 ml)', 'epson-003-original-ink-bottle', 'EPS-003',
  (select id from public.brands where slug = 'epson'),
  (select id from public.categories where slug = 'ink'),
  null,
  'ink_toner', 'Black 4,500 pages • Colour 7,500 pages', 'Genuine Epson 003 ink bottles with keyed nozzles for spill-free refilling of EcoTank L-series printers.', '003', '[{"label":"Part Number","value":"003"},{"label":"Part Type","value":"Ink bottle"},{"label":"Condition","value":"New"},{"label":"Compatible Brands","value":"Epson"},{"label":"Yield","value":"4,500 pages (black), 7,500 pages (colour)"},{"label":"Volume","value":"65 ml"},{"label":"Warranty","value":"3 months"}]'::jsonb,
  array['Keyed bottle prevents filling the wrong tank', 'Genuine Epson ink protects your printhead']::text[], array['1 × 65 ml ink bottle']::text[], '3 months',
  1150, null, 0, 5, 'active',
  true, true, false, false,
  'Epson 003 Original Ink Bottle (65 ml) Price in Kenya | CISS Solutions', 'Buy Epson 003 Original Ink Bottle (65 ml) in Kenya. Black 4,500 pages • Colour 7,500 pages. Genuine products, nationwide delivery and M-Pesa payment.');
insert into public.product_costs (product_id, cost_price)
values ((select id from public.products where sku = 'EPS-003'), 897);
insert into public.product_images (product_id, url, alt_text, sort_order, is_primary)
values ((select id from public.products where sku = 'EPS-003'), '/images/products/ink-bottle-set.svg', 'Epson 003 Original Ink Bottle (65 ml)', 0, true);
insert into public.product_variants (product_id, name, sku, option_values, price, stock_quantity, image_url, sort_order)
values ((select id from public.products where sku = 'EPS-003'), 'Black', 'EPS-003-BK', '{"Colour":"Black"}'::jsonb, 1150, 40, '/images/products/ink-bottle-black.svg', 0);
insert into public.product_variants (product_id, name, sku, option_values, price, stock_quantity, image_url, sort_order)
values ((select id from public.products where sku = 'EPS-003'), 'Cyan', 'EPS-003-C', '{"Colour":"Cyan"}'::jsonb, 1150, 30, '/images/products/ink-bottle-cyan.svg', 1);
insert into public.product_variants (product_id, name, sku, option_values, price, stock_quantity, image_url, sort_order)
values ((select id from public.products where sku = 'EPS-003'), 'Magenta', 'EPS-003-M', '{"Colour":"Magenta"}'::jsonb, 1150, 28, '/images/products/ink-bottle-magenta.svg', 2);
insert into public.product_variants (product_id, name, sku, option_values, price, stock_quantity, image_url, sort_order)
values ((select id from public.products where sku = 'EPS-003'), 'Yellow', 'EPS-003-Y', '{"Colour":"Yellow"}'::jsonb, 1150, 3, '/images/products/ink-bottle-yellow.svg', 3);
insert into public.product_compatibility (product_id, printer_model_id)
values ((select id from public.products where sku = 'EPS-003'), (select id from public.printer_models where model_number = 'L3250'));
insert into public.product_compatibility (product_id, printer_model_id)
values ((select id from public.products where sku = 'EPS-003'), (select id from public.printer_models where model_number = 'L3210'));
insert into public.product_compatibility (product_id, printer_model_id)
values ((select id from public.products where sku = 'EPS-003'), (select id from public.printer_models where model_number = 'L3150'));
insert into public.product_compatibility (product_id, printer_model_id)
values ((select id from public.products where sku = 'EPS-003'), (select id from public.printer_models where model_number = 'L3110'));
insert into public.product_compatibility (product_id, printer_model_id)
values ((select id from public.products where sku = 'EPS-003'), (select id from public.printer_models where model_number = 'L5290'));

insert into public.products (name, slug, sku, brand_id, category_id, printer_model_id, product_type,
  short_description, description, part_number, specifications, features, whats_included, warranty, price,
  compare_at_price, stock_quantity, low_stock_threshold, status, is_featured, is_bestseller, is_new, is_on_sale,
  seo_title, seo_description)
values ('Canon GI-490 Original Ink Bottle', 'canon-gi-490-ink-bottle', 'CAN-GI490',
  (select id from public.brands where slug = 'canon'),
  (select id from public.categories where slug = 'ink'),
  null,
  'ink_toner', 'Black 6,000 pages • Colour 7,000 pages', 'Genuine Canon GI-490 refill ink for PIXMA G-series ink tank printers.', 'GI-490', '[{"label":"Part Number","value":"GI-490"},{"label":"Part Type","value":"Ink bottle"},{"label":"Condition","value":"New"},{"label":"Compatible Brands","value":"Canon"},{"label":"Yield","value":"6,000 pages (black), 7,000 pages (colour)"},{"label":"Volume","value":"135 ml (black), 70 ml (colour)"},{"label":"Warranty","value":"3 months"}]'::jsonb,
  array['Pigment black for sharp text', 'Dye colours for vibrant photos']::text[], array['1 × ink bottle']::text[], '3 months',
  1100, null, 0, 5, 'active',
  false, false, false, false,
  'Canon GI-490 Original Ink Bottle Price in Kenya | CISS Solutions', 'Buy Canon GI-490 Original Ink Bottle in Kenya. Black 6,000 pages • Colour 7,000 pages. Genuine products, nationwide delivery and M-Pesa payment.');
insert into public.product_costs (product_id, cost_price)
values ((select id from public.products where sku = 'CAN-GI490'), 858);
insert into public.product_images (product_id, url, alt_text, sort_order, is_primary)
values ((select id from public.products where sku = 'CAN-GI490'), '/images/products/ink-bottle-set.svg', 'Canon GI-490 Original Ink Bottle', 0, true);
insert into public.product_variants (product_id, name, sku, option_values, price, stock_quantity, image_url, sort_order)
values ((select id from public.products where sku = 'CAN-GI490'), 'Black (135 ml)', 'CAN-GI490-BK', '{"Colour":"Black"}'::jsonb, 1200, 20, '/images/products/ink-bottle-black.svg', 0);
insert into public.product_variants (product_id, name, sku, option_values, price, stock_quantity, image_url, sort_order)
values ((select id from public.products where sku = 'CAN-GI490'), 'Cyan (70 ml)', 'CAN-GI490-C', '{"Colour":"Cyan"}'::jsonb, 1100, 14, '/images/products/ink-bottle-cyan.svg', 1);
insert into public.product_variants (product_id, name, sku, option_values, price, stock_quantity, image_url, sort_order)
values ((select id from public.products where sku = 'CAN-GI490'), 'Magenta (70 ml)', 'CAN-GI490-M', '{"Colour":"Magenta"}'::jsonb, 1100, 14, '/images/products/ink-bottle-magenta.svg', 2);
insert into public.product_variants (product_id, name, sku, option_values, price, stock_quantity, image_url, sort_order)
values ((select id from public.products where sku = 'CAN-GI490'), 'Yellow (70 ml)', 'CAN-GI490-Y', '{"Colour":"Yellow"}'::jsonb, 1100, 12, '/images/products/ink-bottle-yellow.svg', 3);
insert into public.product_compatibility (product_id, printer_model_id)
values ((select id from public.products where sku = 'CAN-GI490'), (select id from public.printer_models where model_number = 'G3420'));
insert into public.product_compatibility (product_id, printer_model_id)
values ((select id from public.products where sku = 'CAN-GI490'), (select id from public.printer_models where model_number = 'G2410'));
insert into public.product_compatibility (product_id, printer_model_id)
values ((select id from public.products where sku = 'CAN-GI490'), (select id from public.printer_models where model_number = 'G3411'));

insert into public.products (name, slug, sku, brand_id, category_id, printer_model_id, product_type,
  short_description, description, part_number, specifications, features, whats_included, warranty, price,
  compare_at_price, stock_quantity, low_stock_threshold, status, is_featured, is_bestseller, is_new, is_on_sale,
  seo_title, seo_description)
values ('HP 59A Black Original LaserJet Toner Cartridge (CF259A)', 'hp-59a-black-toner-cf259a', 'HP-CF259A',
  (select id from public.brands where slug = 'hp'),
  (select id from public.categories where slug = 'toner'),
  null,
  'ink_toner', 'Approx. 3,000 pages • Black', 'Original HP 59A toner for consistent, sharp mono printing on LaserJet Pro M404 and M405 printers.', 'CF259A', '[{"label":"Part Number","value":"CF259A"},{"label":"OEM Number","value":"HP 59A"},{"label":"Part Type","value":"Toner cartridge"},{"label":"Condition","value":"New"},{"label":"Compatible Brands","value":"HP"},{"label":"Yield","value":"Approx. 3,000 pages (ISO)"},{"label":"Warranty","value":"3 months"}]'::jsonb,
  array['JetIntelligence page-maximising technology', 'Anti-fraud protection']::text[], array['1 × toner cartridge']::text[], '3 months',
  14500, 15800, 14, 5, 'active',
  false, false, false, true,
  'HP 59A Black Original LaserJet Toner Cartridge (CF259A) Price in Kenya | CISS Solutions', 'Buy HP 59A Black Original LaserJet Toner Cartridge (CF259A) in Kenya. Approx. 3,000 pages • Black. Genuine products, nationwide delivery and M-Pesa payment.');
insert into public.product_costs (product_id, cost_price)
values ((select id from public.products where sku = 'HP-CF259A'), 11310);
insert into public.product_images (product_id, url, alt_text, sort_order, is_primary)
values ((select id from public.products where sku = 'HP-CF259A'), '/images/products/toner-black.svg', 'HP 59A Black Original LaserJet Toner Cartridge (CF259A)', 0, true);
insert into public.product_compatibility (product_id, printer_model_id)
values ((select id from public.products where sku = 'HP-CF259A'), (select id from public.printer_models where model_number = 'M404dn'));
insert into public.product_compatibility (product_id, printer_model_id)
values ((select id from public.products where sku = 'HP-CF259A'), (select id from public.printer_models where model_number = 'M404dw'));
insert into public.product_compatibility (product_id, printer_model_id)
values ((select id from public.products where sku = 'HP-CF259A'), (select id from public.printer_models where model_number = 'M405dn'));

insert into public.products (name, slug, sku, brand_id, category_id, printer_model_id, product_type,
  short_description, description, part_number, specifications, features, whats_included, warranty, price,
  compare_at_price, stock_quantity, low_stock_threshold, status, is_featured, is_bestseller, is_new, is_on_sale,
  seo_title, seo_description)
values ('HP 30A Black Original LaserJet Toner Cartridge (CF230A)', 'hp-30a-black-toner-cf230a', 'HP-CF230A',
  (select id from public.brands where slug = 'hp'),
  (select id from public.categories where slug = 'toner'),
  null,
  'ink_toner', 'Approx. 1,600 pages • Black', 'Original HP 30A toner for LaserJet Pro M203 and MFP M227 printers.', 'CF230A', '[{"label":"Part Number","value":"CF230A"},{"label":"OEM Number","value":"HP 30A"},{"label":"Part Type","value":"Toner cartridge"},{"label":"Condition","value":"New"},{"label":"Compatible Brands","value":"HP"},{"label":"Yield","value":"Approx. 1,600 pages (ISO)"},{"label":"Warranty","value":"3 months"}]'::jsonb,
  array['Original HP toner']::text[], array['1 × toner cartridge']::text[], '3 months',
  9999, null, 10, 5, 'active',
  false, false, false, false,
  'HP 30A Black Original LaserJet Toner Cartridge (CF230A) Price in Kenya | CISS Solutions', 'Buy HP 30A Black Original LaserJet Toner Cartridge (CF230A) in Kenya. Approx. 1,600 pages • Black. Genuine products, nationwide delivery and M-Pesa payment.');
insert into public.product_costs (product_id, cost_price)
values ((select id from public.products where sku = 'HP-CF230A'), 7799);
insert into public.product_images (product_id, url, alt_text, sort_order, is_primary)
values ((select id from public.products where sku = 'HP-CF230A'), '/images/products/toner-black.svg', 'HP 30A Black Original LaserJet Toner Cartridge (CF230A)', 0, true);
insert into public.product_compatibility (product_id, printer_model_id)
values ((select id from public.products where sku = 'HP-CF230A'), (select id from public.printer_models where model_number = 'M203dw'));
insert into public.product_compatibility (product_id, printer_model_id)
values ((select id from public.products where sku = 'HP-CF230A'), (select id from public.printer_models where model_number = 'M227fdw'));

insert into public.products (name, slug, sku, brand_id, category_id, printer_model_id, product_type,
  short_description, description, part_number, specifications, features, whats_included, warranty, price,
  compare_at_price, stock_quantity, low_stock_threshold, status, is_featured, is_bestseller, is_new, is_on_sale,
  seo_title, seo_description)
values ('Brother TN-2420 High Yield Toner Cartridge', 'brother-tn-2420-toner', 'BRO-TN2420',
  (select id from public.brands where slug = 'brother'),
  (select id from public.categories where slug = 'toner'),
  null,
  'ink_toner', 'Approx. 3,000 pages • Black', 'High-yield genuine Brother toner for HL-L2350DW and DCP-L2540DW printers.', 'TN-2420', '[{"label":"Part Number","value":"TN-2420"},{"label":"Part Type","value":"Toner cartridge"},{"label":"Condition","value":"New"},{"label":"Compatible Brands","value":"Brother"},{"label":"Yield","value":"Approx. 3,000 pages (ISO)"},{"label":"Warranty","value":"3 months"}]'::jsonb,
  array['Genuine Brother toner']::text[], array['1 × toner cartridge']::text[], '3 months',
  9800, null, 16, 5, 'active',
  false, false, false, false,
  'Brother TN-2420 High Yield Toner Cartridge Price in Kenya | CISS Solutions', 'Buy Brother TN-2420 High Yield Toner Cartridge in Kenya. Approx. 3,000 pages • Black. Genuine products, nationwide delivery and M-Pesa payment.');
insert into public.product_costs (product_id, cost_price)
values ((select id from public.products where sku = 'BRO-TN2420'), 7644);
insert into public.product_images (product_id, url, alt_text, sort_order, is_primary)
values ((select id from public.products where sku = 'BRO-TN2420'), '/images/products/toner-blue-band.svg', 'Brother TN-2420 High Yield Toner Cartridge', 0, true);
insert into public.product_compatibility (product_id, printer_model_id)
values ((select id from public.products where sku = 'BRO-TN2420'), (select id from public.printer_models where model_number = 'HL-L2350DW'));
insert into public.product_compatibility (product_id, printer_model_id)
values ((select id from public.products where sku = 'BRO-TN2420'), (select id from public.printer_models where model_number = 'DCP-L2540DW'));

insert into public.products (name, slug, sku, brand_id, category_id, printer_model_id, product_type,
  short_description, description, part_number, specifications, features, whats_included, warranty, price,
  compare_at_price, stock_quantity, low_stock_threshold, status, is_featured, is_bestseller, is_new, is_on_sale,
  seo_title, seo_description)
values ('Brother DR-2405 Drum Unit', 'brother-dr-2405-drum-unit', 'BRO-DR2405',
  (select id from public.brands where slug = 'brother'),
  (select id from public.categories where slug = 'toner'),
  null,
  'spare_part', 'Approx. 12,000 pages', 'Replacement drum unit. Replace when the printer reports "Replace Drum" or prints show repeating marks.', 'DR-2405', '[{"label":"Part Number","value":"DR-2405"},{"label":"Part Type","value":"Drum unit"},{"label":"Condition","value":"New"},{"label":"Compatible Brands","value":"Brother"},{"label":"Yield","value":"Approx. 12,000 pages"},{"label":"Warranty","value":"3 months"}]'::jsonb,
  array['Genuine Brother drum']::text[], array['1 × drum unit']::text[], '3 months',
  8500, null, 5, 5, 'active',
  false, false, false, false,
  'Brother DR-2405 Drum Unit Price in Kenya | CISS Solutions', 'Buy Brother DR-2405 Drum Unit in Kenya. Approx. 12,000 pages. Genuine products, nationwide delivery and M-Pesa payment.');
insert into public.product_costs (product_id, cost_price)
values ((select id from public.products where sku = 'BRO-DR2405'), 6630);
insert into public.product_images (product_id, url, alt_text, sort_order, is_primary)
values ((select id from public.products where sku = 'BRO-DR2405'), '/images/products/drum-unit.svg', 'Brother DR-2405 Drum Unit', 0, true);
insert into public.product_compatibility (product_id, printer_model_id)
values ((select id from public.products where sku = 'BRO-DR2405'), (select id from public.printer_models where model_number = 'HL-L2350DW'));
insert into public.product_compatibility (product_id, printer_model_id)
values ((select id from public.products where sku = 'BRO-DR2405'), (select id from public.printer_models where model_number = 'DCP-L2540DW'));

insert into public.products (name, slug, sku, brand_id, category_id, printer_model_id, product_type,
  short_description, description, part_number, specifications, features, whats_included, warranty, price,
  compare_at_price, stock_quantity, low_stock_threshold, status, is_featured, is_bestseller, is_new, is_on_sale,
  seo_title, seo_description)
values ('Brother BTD60BK Black Ink Bottle', 'brother-btd60bk-black-ink', 'BRO-BTD60BK',
  (select id from public.brands where slug = 'brother'),
  (select id from public.categories where slug = 'ink'),
  null,
  'ink_toner', 'Approx. 6,500 pages • Black', 'Genuine Brother pigment black ink bottle for DCP-T series ink tank printers.', 'BTD60BK', '[{"label":"Part Number","value":"BTD60BK"},{"label":"Part Type","value":"Ink bottle"},{"label":"Condition","value":"New"},{"label":"Compatible Brands","value":"Brother"},{"label":"Yield","value":"Approx. 6,500 pages"},{"label":"Volume","value":"108 ml"},{"label":"Warranty","value":"3 months"}]'::jsonb,
  array['Pigment ink for crisp text']::text[], array['1 × 108 ml ink bottle']::text[], '3 months',
  1450, null, 20, 5, 'active',
  false, false, false, false,
  'Brother BTD60BK Black Ink Bottle Price in Kenya | CISS Solutions', 'Buy Brother BTD60BK Black Ink Bottle in Kenya. Approx. 6,500 pages • Black. Genuine products, nationwide delivery and M-Pesa payment.');
insert into public.product_costs (product_id, cost_price)
values ((select id from public.products where sku = 'BRO-BTD60BK'), 1131);
insert into public.product_images (product_id, url, alt_text, sort_order, is_primary)
values ((select id from public.products where sku = 'BRO-BTD60BK'), '/images/products/ink-bottle-black.svg', 'Brother BTD60BK Black Ink Bottle', 0, true);
insert into public.product_compatibility (product_id, printer_model_id)
values ((select id from public.products where sku = 'BRO-BTD60BK'), (select id from public.printer_models where model_number = 'DCP-T420W'));
insert into public.product_compatibility (product_id, printer_model_id)
values ((select id from public.products where sku = 'BRO-BTD60BK'), (select id from public.printer_models where model_number = 'DCP-T520W'));

insert into public.products (name, slug, sku, brand_id, category_id, printer_model_id, product_type,
  short_description, description, part_number, specifications, features, whats_included, warranty, price,
  compare_at_price, stock_quantity, low_stock_threshold, status, is_featured, is_bestseller, is_new, is_on_sale,
  seo_title, seo_description)
values ('Pantum PC-211EV Toner Cartridge', 'pantum-pc-211ev-toner', 'PAN-PC211EV',
  (select id from public.brands where slug = 'pantum'),
  (select id from public.categories where slug = 'toner'),
  null,
  'ink_toner', 'Approx. 1,600 pages • Black', 'Original Pantum toner for P2500 series printers.', 'PC-211EV', '[{"label":"Part Number","value":"PC-211EV"},{"label":"Part Type","value":"Toner cartridge"},{"label":"Condition","value":"New"},{"label":"Compatible Brands","value":"Pantum"},{"label":"Yield","value":"Approx. 1,600 pages"},{"label":"Warranty","value":"3 months"}]'::jsonb,
  array['Easy drop-in replacement']::text[], array['1 × toner cartridge']::text[], '3 months',
  4800, null, 30, 5, 'active',
  false, true, false, false,
  'Pantum PC-211EV Toner Cartridge Price in Kenya | CISS Solutions', 'Buy Pantum PC-211EV Toner Cartridge in Kenya. Approx. 1,600 pages • Black. Genuine products, nationwide delivery and M-Pesa payment.');
insert into public.product_costs (product_id, cost_price)
values ((select id from public.products where sku = 'PAN-PC211EV'), 3744);
insert into public.product_images (product_id, url, alt_text, sort_order, is_primary)
values ((select id from public.products where sku = 'PAN-PC211EV'), '/images/products/toner-light.svg', 'Pantum PC-211EV Toner Cartridge', 0, true);
insert into public.product_compatibility (product_id, printer_model_id)
values ((select id from public.products where sku = 'PAN-PC211EV'), (select id from public.printer_models where model_number = 'P2500W'));

insert into public.products (name, slug, sku, brand_id, category_id, printer_model_id, product_type,
  short_description, description, part_number, specifications, features, whats_included, warranty, price,
  compare_at_price, stock_quantity, low_stock_threshold, status, is_featured, is_bestseller, is_new, is_on_sale,
  seo_title, seo_description)
values ('Kyocera TK-1160 Toner Kit', 'kyocera-tk-1160-toner', 'KYO-TK1160',
  (select id from public.brands where slug = 'kyocera'),
  (select id from public.categories where slug = 'toner'),
  null,
  'ink_toner', 'Approx. 7,200 pages • Black', 'Genuine Kyocera toner kit for ECOSYS P2040dn and P2040dw.', 'TK-1160', '[{"label":"Part Number","value":"TK-1160"},{"label":"Part Type","value":"Toner kit"},{"label":"Condition","value":"New"},{"label":"Compatible Brands","value":"Kyocera"},{"label":"Yield","value":"Approx. 7,200 pages"},{"label":"Warranty","value":"3 months"}]'::jsonb,
  array['Long-life toner']::text[], array['1 × toner kit', 'Waste toner bag']::text[], '3 months',
  11500, null, 8, 5, 'active',
  false, false, false, false,
  'Kyocera TK-1160 Toner Kit Price in Kenya | CISS Solutions', 'Buy Kyocera TK-1160 Toner Kit in Kenya. Approx. 7,200 pages • Black. Genuine products, nationwide delivery and M-Pesa payment.');
insert into public.product_costs (product_id, cost_price)
values ((select id from public.products where sku = 'KYO-TK1160'), 8970);
insert into public.product_images (product_id, url, alt_text, sort_order, is_primary)
values ((select id from public.products where sku = 'KYO-TK1160'), '/images/products/toner-black.svg', 'Kyocera TK-1160 Toner Kit', 0, true);
insert into public.product_compatibility (product_id, printer_model_id)
values ((select id from public.products where sku = 'KYO-TK1160'), (select id from public.printer_models where model_number = 'P2040dn'));

insert into public.products (name, slug, sku, brand_id, category_id, printer_model_id, product_type,
  short_description, description, part_number, specifications, features, whats_included, warranty, price,
  compare_at_price, stock_quantity, low_stock_threshold, status, is_featured, is_bestseller, is_new, is_on_sale,
  seo_title, seo_description)
values ('HP LaserJet Pro M404 / M405 Pickup Roller', 'hp-laserjet-m404-m405-pickup-roller', 'SP-RM2-5452',
  (select id from public.brands where slug = 'hp'),
  (select id from public.categories where slug = 'pickup-rollers'),
  null,
  'spare_part', 'Fixes misfeeds and paper jams from Tray 2', 'Replacement Tray 2 pickup roller for HP LaserJet Pro M404 and M405 printers. A worn pickup roller is the most common cause of "paper jam" and "load paper" errors when paper is in the tray.', 'RM2-5452-000', '[{"label":"Part Number","value":"RM2-5452-000"},{"label":"Part Type","value":"Pickup roller"},{"label":"Condition","value":"New (compatible)"},{"label":"Compatible Brands","value":"HP"},{"label":"Warranty","value":"3 months"}]'::jsonb,
  array['Restores reliable paper pickup', 'Tool-free installation in minutes']::text[], array['1 × pickup roller assembly']::text[], '3 months',
  2500, null, 24, 5, 'active',
  true, true, false, false,
  'HP LaserJet Pro M404 / M405 Pickup Roller Price in Kenya | CISS Solutions', 'Buy HP LaserJet Pro M404 / M405 Pickup Roller in Kenya. Fixes misfeeds and paper jams from Tray 2. Genuine products, nationwide delivery and M-Pesa payment.');
insert into public.product_costs (product_id, cost_price)
values ((select id from public.products where sku = 'SP-RM2-5452'), 1950);
insert into public.product_images (product_id, url, alt_text, sort_order, is_primary)
values ((select id from public.products where sku = 'SP-RM2-5452'), '/images/products/pickup-roller.svg', 'HP LaserJet Pro M404 / M405 Pickup Roller', 0, true);
insert into public.product_compatibility (product_id, printer_model_id)
values ((select id from public.products where sku = 'SP-RM2-5452'), (select id from public.printer_models where model_number = 'M404dn'));
insert into public.product_compatibility (product_id, printer_model_id)
values ((select id from public.products where sku = 'SP-RM2-5452'), (select id from public.printer_models where model_number = 'M404dw'));
insert into public.product_compatibility (product_id, printer_model_id)
values ((select id from public.products where sku = 'SP-RM2-5452'), (select id from public.printer_models where model_number = 'M405dn'));

insert into public.products (name, slug, sku, brand_id, category_id, printer_model_id, product_type,
  short_description, description, part_number, specifications, features, whats_included, warranty, price,
  compare_at_price, stock_quantity, low_stock_threshold, status, is_featured, is_bestseller, is_new, is_on_sale,
  seo_title, seo_description)
values ('HP LaserJet Pro M404 / M405 Fuser Unit (220V)', 'hp-laserjet-m404-m405-fuser-unit-220v', 'SP-RM2-5399',
  (select id from public.brands where slug = 'hp'),
  (select id from public.categories where slug = 'fuser-units'),
  null,
  'spare_part', '220V • Fixes smudged or unfused prints', 'Fuser assembly for HP LaserJet Pro M404/M405. Replace when prints smudge, toner rubs off or the printer reports a fuser error (50.x).', 'RM2-5399-000', '[{"label":"Part Number","value":"RM2-5399-000"},{"label":"Part Type","value":"Fuser unit"},{"label":"Condition","value":"New (compatible)"},{"label":"Compatible Brands","value":"HP"},{"label":"Warranty","value":"3 months"}]'::jsonb,
  array['220V version for Kenya']::text[], array['1 × fuser assembly']::text[], '3 months',
  18500, null, 3, 5, 'active',
  false, false, false, false,
  'HP LaserJet Pro M404 / M405 Fuser Unit (220V) Price in Kenya | CISS Solutions', 'Buy HP LaserJet Pro M404 / M405 Fuser Unit (220V) in Kenya. 220V • Fixes smudged or unfused prints. Genuine products, nationwide delivery and M-Pesa payment.');
insert into public.product_costs (product_id, cost_price)
values ((select id from public.products where sku = 'SP-RM2-5399'), 14430);
insert into public.product_images (product_id, url, alt_text, sort_order, is_primary)
values ((select id from public.products where sku = 'SP-RM2-5399'), '/images/products/fuser-unit.svg', 'HP LaserJet Pro M404 / M405 Fuser Unit (220V)', 0, true);
insert into public.product_compatibility (product_id, printer_model_id)
values ((select id from public.products where sku = 'SP-RM2-5399'), (select id from public.printer_models where model_number = 'M404dn'));
insert into public.product_compatibility (product_id, printer_model_id)
values ((select id from public.products where sku = 'SP-RM2-5399'), (select id from public.printer_models where model_number = 'M404dw'));
insert into public.product_compatibility (product_id, printer_model_id)
values ((select id from public.products where sku = 'SP-RM2-5399'), (select id from public.printer_models where model_number = 'M405dn'));

insert into public.products (name, slug, sku, brand_id, category_id, printer_model_id, product_type,
  short_description, description, part_number, specifications, features, whats_included, warranty, price,
  compare_at_price, stock_quantity, low_stock_threshold, status, is_featured, is_bestseller, is_new, is_on_sale,
  seo_title, seo_description)
values ('Epson L3110 / L3150 / L3210 / L3250 Printhead', 'epson-l3110-l3150-l3250-printhead', 'SP-FA04010',
  (select id from public.brands where slug = 'epson'),
  (select id from public.categories where slug = 'printheads'),
  null,
  'spare_part', 'Fixes missing colours and banding', 'Replacement printhead for Epson EcoTank L3110, L3150, L3210 and L3250. Fit when head cleaning no longer restores missing colours or lines.', 'FA04010', '[{"label":"Part Number","value":"FA04010"},{"label":"OEM Number","value":"FA04000"},{"label":"Part Type","value":"Printhead"},{"label":"Condition","value":"New (original)"},{"label":"Compatible Brands","value":"Epson"},{"label":"Warranty","value":"3 months"}]'::jsonb,
  array['Original Epson printhead']::text[], array['1 × printhead']::text[], '3 months',
  9500, 10500, 6, 5, 'active',
  true, false, false, false,
  'Epson L3110 / L3150 / L3210 / L3250 Printhead Price in Kenya | CISS Solutions', 'Buy Epson L3110 / L3150 / L3210 / L3250 Printhead in Kenya. Fixes missing colours and banding. Genuine products, nationwide delivery and M-Pesa payment.');
insert into public.product_costs (product_id, cost_price)
values ((select id from public.products where sku = 'SP-FA04010'), 7410);
insert into public.product_images (product_id, url, alt_text, sort_order, is_primary)
values ((select id from public.products where sku = 'SP-FA04010'), '/images/products/printhead.svg', 'Epson L3110 / L3150 / L3210 / L3250 Printhead', 0, true);
insert into public.product_compatibility (product_id, printer_model_id)
values ((select id from public.products where sku = 'SP-FA04010'), (select id from public.printer_models where model_number = 'L3110'));
insert into public.product_compatibility (product_id, printer_model_id)
values ((select id from public.products where sku = 'SP-FA04010'), (select id from public.printer_models where model_number = 'L3150'));
insert into public.product_compatibility (product_id, printer_model_id)
values ((select id from public.products where sku = 'SP-FA04010'), (select id from public.printer_models where model_number = 'L3210'));
insert into public.product_compatibility (product_id, printer_model_id)
values ((select id from public.products where sku = 'SP-FA04010'), (select id from public.printer_models where model_number = 'L3250'));

insert into public.products (name, slug, sku, brand_id, category_id, printer_model_id, product_type,
  short_description, description, part_number, specifications, features, whats_included, warranty, price,
  compare_at_price, stock_quantity, low_stock_threshold, status, is_featured, is_bestseller, is_new, is_on_sale,
  seo_title, seo_description)
values ('Epson L-Series Waste Ink Pad Maintenance Kit', 'epson-l-series-waste-ink-pad-kit', 'SP-EPS-PADKIT',
  (select id from public.brands where slug = 'epson'),
  (select id from public.categories where slug = 'maintenance-kits'),
  null,
  'spare_part', 'For "service required" / red-light errors', 'Replacement waste ink absorber pads for Epson L-series printers. Pair with an ink pad counter reset when the printer shows "Service Required".', 'EPS-PAD-L3', '[{"label":"Part Number","value":"EPS-PAD-L3"},{"label":"Part Type","value":"Waste ink pads"},{"label":"Condition","value":"New (compatible)"},{"label":"Compatible Brands","value":"Epson"},{"label":"Warranty","value":"3 months"}]'::jsonb,
  array['High-absorption pads']::text[], array['Waste ink pad set']::text[], '3 months',
  1200, null, 35, 5, 'active',
  false, false, false, false,
  'Epson L-Series Waste Ink Pad Maintenance Kit Price in Kenya | CISS Solutions', 'Buy Epson L-Series Waste Ink Pad Maintenance Kit in Kenya. For "service required" / red-light errors. Genuine products, nationwide delivery and M-Pesa payment.');
insert into public.product_costs (product_id, cost_price)
values ((select id from public.products where sku = 'SP-EPS-PADKIT'), 936);
insert into public.product_images (product_id, url, alt_text, sort_order, is_primary)
values ((select id from public.products where sku = 'SP-EPS-PADKIT'), '/images/products/maintenance-kit.svg', 'Epson L-Series Waste Ink Pad Maintenance Kit', 0, true);
insert into public.product_compatibility (product_id, printer_model_id)
values ((select id from public.products where sku = 'SP-EPS-PADKIT'), (select id from public.printer_models where model_number = 'L3110'));
insert into public.product_compatibility (product_id, printer_model_id)
values ((select id from public.products where sku = 'SP-EPS-PADKIT'), (select id from public.printer_models where model_number = 'L3150'));
insert into public.product_compatibility (product_id, printer_model_id)
values ((select id from public.products where sku = 'SP-EPS-PADKIT'), (select id from public.printer_models where model_number = 'L3210'));
insert into public.product_compatibility (product_id, printer_model_id)
values ((select id from public.products where sku = 'SP-EPS-PADKIT'), (select id from public.printer_models where model_number = 'L3250'));
insert into public.product_compatibility (product_id, printer_model_id)
values ((select id from public.products where sku = 'SP-EPS-PADKIT'), (select id from public.printer_models where model_number = 'L5290'));

insert into public.products (name, slug, sku, brand_id, category_id, printer_model_id, product_type,
  short_description, description, part_number, specifications, features, whats_included, warranty, price,
  compare_at_price, stock_quantity, low_stock_threshold, status, is_featured, is_bestseller, is_new, is_on_sale,
  seo_title, seo_description)
values ('Canon PIXMA G-Series Paper Feed Roller', 'canon-pixma-g-series-paper-feed-roller', 'SP-CAN-GFEED',
  (select id from public.brands where slug = 'canon'),
  (select id from public.categories where slug = 'paper-feed-parts'),
  null,
  'spare_part', 'Rear tray paper feed roller', 'Paper feed roller for Canon PIXMA G2410, G3411 and G3420. Fixes paper not feeding from the rear tray.', 'QM7-xxxx', '[{"label":"Part Number","value":"QM7-xxxx"},{"label":"Part Type","value":"Paper feed roller"},{"label":"Condition","value":"New (compatible)"},{"label":"Compatible Brands","value":"Canon"},{"label":"Warranty","value":"3 months"}]'::jsonb,
  array['Restores reliable feeding']::text[], array['1 × feed roller']::text[], '3 months',
  1800, null, 9, 5, 'active',
  false, false, true, false,
  'Canon PIXMA G-Series Paper Feed Roller Price in Kenya | CISS Solutions', 'Buy Canon PIXMA G-Series Paper Feed Roller in Kenya. Rear tray paper feed roller. Genuine products, nationwide delivery and M-Pesa payment.');
insert into public.product_costs (product_id, cost_price)
values ((select id from public.products where sku = 'SP-CAN-GFEED'), 1404);
insert into public.product_images (product_id, url, alt_text, sort_order, is_primary)
values ((select id from public.products where sku = 'SP-CAN-GFEED'), '/images/products/pickup-roller.svg', 'Canon PIXMA G-Series Paper Feed Roller', 0, true);
insert into public.product_compatibility (product_id, printer_model_id)
values ((select id from public.products where sku = 'SP-CAN-GFEED'), (select id from public.printer_models where model_number = 'G3420'));
insert into public.product_compatibility (product_id, printer_model_id)
values ((select id from public.products where sku = 'SP-CAN-GFEED'), (select id from public.printer_models where model_number = 'G2410'));
insert into public.product_compatibility (product_id, printer_model_id)
values ((select id from public.products where sku = 'SP-CAN-GFEED'), (select id from public.printer_models where model_number = 'G3411'));

insert into public.products (name, slug, sku, brand_id, category_id, printer_model_id, product_type,
  short_description, description, part_number, specifications, features, whats_included, warranty, price,
  compare_at_price, stock_quantity, low_stock_threshold, status, is_featured, is_bestseller, is_new, is_on_sale,
  seo_title, seo_description)
values ('Epson Perfection V39 II Flatbed Photo Scanner', 'epson-perfection-v39-ii-scanner', 'EPS-V39II',
  (select id from public.brands where slug = 'epson'),
  (select id from public.categories where slug = 'scanners'),
  null,
  'scanner', '4800 dpi • USB powered', 'Slim USB-powered flatbed scanner for documents and photos with scan-to-cloud.', null, '[{"label":"Scanner Type","value":"Flatbed"},{"label":"Optical Resolution","value":"4800 × 4800 dpi"},{"label":"Interface","value":"USB 2.0 (bus powered)"},{"label":"Max Scan Size","value":"A4"},{"label":"Warranty","value":"1 year"}]'::jsonb,
  array['Scan to cloud', 'Removable lid for books']::text[], array['Scanner', 'USB cable']::text[], '1 year',
  18999, null, 5, 5, 'active',
  false, false, false, false,
  'Epson Perfection V39 II Flatbed Photo Scanner Price in Kenya | CISS Solutions', 'Buy Epson Perfection V39 II Flatbed Photo Scanner in Kenya. 4800 dpi • USB powered. Genuine products, nationwide delivery and M-Pesa payment.');
insert into public.product_costs (product_id, cost_price)
values ((select id from public.products where sku = 'EPS-V39II'), 14819);
insert into public.product_images (product_id, url, alt_text, sort_order, is_primary)
values ((select id from public.products where sku = 'EPS-V39II'), '/images/products/scanner.svg', 'Epson Perfection V39 II Flatbed Photo Scanner', 0, true);

insert into public.products (name, slug, sku, brand_id, category_id, printer_model_id, product_type,
  short_description, description, part_number, specifications, features, whats_included, warranty, price,
  compare_at_price, stock_quantity, low_stock_threshold, status, is_featured, is_bestseller, is_new, is_on_sale,
  seo_title, seo_description)
values ('Canon CanoScan LiDE 300 Flatbed Scanner', 'canon-canoscan-lide-300', 'CAN-LIDE300',
  (select id from public.brands where slug = 'canon'),
  (select id from public.categories where slug = 'scanners'),
  null,
  'scanner', '2400 dpi • USB powered', 'Compact, affordable flatbed scanner for everyday documents and photos.', null, '[{"label":"Scanner Type","value":"Flatbed"},{"label":"Optical Resolution","value":"2400 × 2400 dpi"},{"label":"Interface","value":"USB 2.0 (bus powered)"},{"label":"Max Scan Size","value":"A4"},{"label":"Warranty","value":"1 year"}]'::jsonb,
  array['One-touch scan buttons']::text[], array['Scanner', 'USB cable']::text[], '1 year',
  11500, 12500, 7, 5, 'active',
  false, false, false, true,
  'Canon CanoScan LiDE 300 Flatbed Scanner Price in Kenya | CISS Solutions', 'Buy Canon CanoScan LiDE 300 Flatbed Scanner in Kenya. 2400 dpi • USB powered. Genuine products, nationwide delivery and M-Pesa payment.');
insert into public.product_costs (product_id, cost_price)
values ((select id from public.products where sku = 'CAN-LIDE300'), 8970);
insert into public.product_images (product_id, url, alt_text, sort_order, is_primary)
values ((select id from public.products where sku = 'CAN-LIDE300'), '/images/products/scanner.svg', 'Canon CanoScan LiDE 300 Flatbed Scanner', 0, true);

insert into public.products (name, slug, sku, brand_id, category_id, printer_model_id, product_type,
  short_description, description, part_number, specifications, features, whats_included, warranty, price,
  compare_at_price, stock_quantity, low_stock_threshold, status, is_featured, is_bestseller, is_new, is_on_sale,
  seo_title, seo_description)
values ('Premium Copy Paper Ream (500 sheets)', 'premium-copy-paper-ream', 'PAP-COPY',
  null,
  (select id from public.categories where slug = 'paper-media'),
  null,
  'paper', 'A4 / A3 • 80 – 100 gsm', 'Bright white multipurpose copy paper for laser and inkjet printers and copiers.', null, '[{"label":"Sheets","value":"500 per ream"},{"label":"Brightness","value":"CIE 161"},{"label":"Use","value":"Laser, inkjet, copier"}]'::jsonb,
  array['Jam-free performance']::text[], array['1 ream (500 sheets)']::text[], null,
  750, null, 0, 5, 'active',
  false, true, false, false,
  'Premium Copy Paper Ream (500 sheets) Price in Kenya | CISS Solutions', 'Buy Premium Copy Paper Ream (500 sheets) in Kenya. A4 / A3 • 80 – 100 gsm. Genuine products, nationwide delivery and M-Pesa payment.');
insert into public.product_costs (product_id, cost_price)
values ((select id from public.products where sku = 'PAP-COPY'), 585);
insert into public.product_images (product_id, url, alt_text, sort_order, is_primary)
values ((select id from public.products where sku = 'PAP-COPY'), '/images/products/paper-ream.svg', 'Premium Copy Paper Ream (500 sheets)', 0, true);
insert into public.product_images (product_id, url, alt_text, sort_order, is_primary)
values ((select id from public.products where sku = 'PAP-COPY'), '/images/products/paper-ream-a3.svg', 'Premium Copy Paper Ream (500 sheets) – view 2', 1, false);
insert into public.product_variants (product_id, name, sku, option_values, price, stock_quantity, image_url, sort_order)
values ((select id from public.products where sku = 'PAP-COPY'), 'A4 80gsm', 'PAP-A4-80', '{"Size":"A4","Weight":"80gsm"}'::jsonb, 750, 120, '/images/products/paper-ream.svg', 0);
insert into public.product_variants (product_id, name, sku, option_values, price, stock_quantity, image_url, sort_order)
values ((select id from public.products where sku = 'PAP-COPY'), 'A4 100gsm', 'PAP-A4-100', '{"Size":"A4","Weight":"100gsm"}'::jsonb, 1150, 40, '/images/products/paper-ream.svg', 1);
insert into public.product_variants (product_id, name, sku, option_values, price, stock_quantity, image_url, sort_order)
values ((select id from public.products where sku = 'PAP-COPY'), 'A3 80gsm', 'PAP-A3-80', '{"Size":"A3","Weight":"80gsm"}'::jsonb, 1650, 25, '/images/products/paper-ream-a3.svg', 2);

insert into public.products (name, slug, sku, brand_id, category_id, printer_model_id, product_type,
  short_description, description, part_number, specifications, features, whats_included, warranty, price,
  compare_at_price, stock_quantity, low_stock_threshold, status, is_featured, is_bestseller, is_new, is_on_sale,
  seo_title, seo_description)
values ('Epson Premium Glossy Photo Paper A4 (20 sheets)', 'epson-premium-glossy-photo-paper-a4', 'EPS-GLOSSY-A4',
  (select id from public.brands where slug = 'epson'),
  (select id from public.categories where slug = 'paper-media'),
  null,
  'paper', '255 gsm • Instant dry', 'Instant-dry glossy photo paper for vivid, long-lasting prints.', null, '[{"label":"Size","value":"A4"},{"label":"Weight","value":"255 gsm"},{"label":"Finish","value":"Glossy"},{"label":"Sheets","value":"20"}]'::jsonb,
  array['Instant dry']::text[], array['20 sheets']::text[], null,
  1200, null, 18, 5, 'active',
  false, false, false, false,
  'Epson Premium Glossy Photo Paper A4 (20 sheets) Price in Kenya | CISS Solutions', 'Buy Epson Premium Glossy Photo Paper A4 (20 sheets) in Kenya. 255 gsm • Instant dry. Genuine products, nationwide delivery and M-Pesa payment.');
insert into public.product_costs (product_id, cost_price)
values ((select id from public.products where sku = 'EPS-GLOSSY-A4'), 936);
insert into public.product_images (product_id, url, alt_text, sort_order, is_primary)
values ((select id from public.products where sku = 'EPS-GLOSSY-A4'), '/images/products/photo-paper.svg', 'Epson Premium Glossy Photo Paper A4 (20 sheets)', 0, true);

insert into public.products (name, slug, sku, brand_id, category_id, printer_model_id, product_type,
  short_description, description, part_number, specifications, features, whats_included, warranty, price,
  compare_at_price, stock_quantity, low_stock_threshold, status, is_featured, is_bestseller, is_new, is_on_sale,
  seo_title, seo_description)
values ('USB 2.0 Printer Cable (A to B)', 'usb-printer-cable-a-to-b', 'ACC-USB-AB',
  null,
  (select id from public.categories where slug = 'cables'),
  null,
  'accessory', 'Shielded • 1.5 m / 3 m', 'Shielded USB 2.0 A-to-B cable that connects most printers and scanners to a computer.', null, '[{"label":"Connector","value":"USB-A male to USB-B male"},{"label":"Standard","value":"USB 2.0"},{"label":"Shielding","value":"Foil + braid"}]'::jsonb,
  array['Gold-plated connectors']::text[], array['1 × cable']::text[], null,
  450, null, 0, 5, 'active',
  false, false, false, false,
  'USB 2.0 Printer Cable (A to B) Price in Kenya | CISS Solutions', 'Buy USB 2.0 Printer Cable (A to B) in Kenya. Shielded • 1.5 m / 3 m. Genuine products, nationwide delivery and M-Pesa payment.');
insert into public.product_costs (product_id, cost_price)
values ((select id from public.products where sku = 'ACC-USB-AB'), 351);
insert into public.product_images (product_id, url, alt_text, sort_order, is_primary)
values ((select id from public.products where sku = 'ACC-USB-AB'), '/images/products/usb-cable.svg', 'USB 2.0 Printer Cable (A to B)', 0, true);
insert into public.product_variants (product_id, name, sku, option_values, price, stock_quantity, image_url, sort_order)
values ((select id from public.products where sku = 'ACC-USB-AB'), '1.5 m', 'ACC-USB-AB-15', '{"Length":"1.5 m"}'::jsonb, 450, 60, '/images/products/usb-cable.svg', 0);
insert into public.product_variants (product_id, name, sku, option_values, price, stock_quantity, image_url, sort_order)
values ((select id from public.products where sku = 'ACC-USB-AB'), '3 m', 'ACC-USB-AB-30', '{"Length":"3 m"}'::jsonb, 650, 30, '/images/products/usb-cable.svg', 1);

insert into public.reviews (product_id, user_id, author_name, rating, title, comment, status, is_verified_purchase)
values ((select id from public.products where sku = 'EPS-L3250'), '00000000-0000-4000-8000-000000000002', 'Wanjiku', 5, 'Excellent value', 'Set up in 10 minutes and the ink lasts forever. Printing from my phone over Wi-Fi works perfectly.', 'approved', true);
insert into public.reviews (product_id, user_id, author_name, rating, title, comment, status, is_verified_purchase)
values ((select id from public.products where sku = 'EPS-L3250'), '00000000-0000-4000-8000-000000000003', 'Brian', 4, 'Great printer for home office', 'Prints are sharp and the running cost is very low. Scanning is a bit slow but fine.', 'approved', true);
insert into public.reviews (product_id, user_id, author_name, rating, title, comment, status, is_verified_purchase)
values ((select id from public.products where sku = 'EPS-L3250'), '00000000-0000-4000-8000-000000000004', 'Amina', 5, 'Fast delivery in Nairobi', 'Ordered in the morning, delivered the same day. Genuine product with warranty.', 'approved', true);
insert into public.reviews (product_id, user_id, author_name, rating, title, comment, status, is_verified_purchase)
values ((select id from public.products where sku = 'HP-M404DN'), '00000000-0000-4000-8000-000000000002', 'Wanjiku', 5, 'Workhorse', 'Fast, quiet and duplex works great. Our office prints 2,000 pages a month on it.', 'approved', true);
insert into public.reviews (product_id, user_id, author_name, rating, title, comment, status, is_verified_purchase)
values ((select id from public.products where sku = 'SP-RM2-5452'), '00000000-0000-4000-8000-000000000003', 'Brian', 5, 'Fixed our paper jams', 'Our M404 kept saying paper jam. Replaced this roller and it works like new.', 'approved', true);
insert into public.reviews (product_id, user_id, author_name, rating, title, comment, status, is_verified_purchase)
values ((select id from public.products where sku = 'EPS-003'), '00000000-0000-4000-8000-000000000004', 'Amina', 5, 'Genuine ink', 'Original Epson bottles, good price.', 'approved', true);
insert into public.reviews (product_id, user_id, author_name, rating, title, comment, status, is_verified_purchase)
values ((select id from public.products where sku = 'PAN-P2500W'), '00000000-0000-4000-8000-000000000003', 'Brian', 4, 'Good budget laser', 'Great for school work. Wi-Fi setup took a few tries.', 'approved', true);

insert into public.homepage_banners (eyebrow, title, highlight, subtitle, image_url, image_alt, cta_text, cta_url,
  secondary_cta_text, secondary_cta_url, featured_product_id, sort_order) values
  ('In stock', 'Epson EcoTank L3250', null,
   'Refillable ink tanks for a low cost per page. Prints, scans and copies over Wi-Fi.',
   '/images/products/printer-inktank-black.svg', 'Epson EcoTank ink tank printer', 'View printer', '/p/epson-ecotank-l3250-all-in-one-printer', 'All ink tank printers', '/c/printers/ink-tank',
   (select id from public.products where sku = 'EPS-L3250'), 10),
  ('For the office', 'Mono laser printers', null,
   'Duplex, networked laser printers from HP, Brother, Kyocera and Pantum, with toner to match.',
   '/images/products/printer-laser-white.svg', 'Mono laser printer', 'Shop laser printers', '/c/printers/laser', 'Find toner', '/c/ink-toner/toner',
   (select id from public.products where sku = 'HP-M404DN'), 20),
  ('Spare parts', 'Rollers, printheads and fusers', null,
   'Matched to your printer model. Not sure what you need? Send us the model and the problem.',
   '/images/products/printhead.svg', 'Printer printhead spare part', 'Find a part', '/parts-finder', 'Ask a technician', '/support/part-request',
   (select id from public.products where sku = 'SP-FA04010'), 30);

insert into public.coupons (code, description, discount_type, value, minimum_order, maximum_discount, usage_limit, per_customer_limit)
values ('CISS10', '10% off orders over KSh 5,000', 'percentage', 10, 5000, 5000, 1000, 1),
       ('INK500', 'KSh 500 off ink and toner over KSh 3,000', 'fixed', 500, 3000, null, null, 3);
update public.coupons set applicable_category_ids = array[(select id from public.categories where slug = 'ink-toner')]
 where code = 'INK500';

update public.settings set value = value || '{"phone":"+254 700 000 000","whatsapp":"254700000000","email":"info@cisssolutions.co.ke","address":"Nairobi CBD, Kenya"}'::jsonb where key = 'business';

commit;
