// Development catalogue. `node scripts/seed/generate.mjs` turns this into supabase/seed.sql.
// Prices are realistic Kenyan retail examples, not live pricing.

export const brands = [
  ['Epson', 'epson', 'Epson EcoTank printers, original ink bottles, scanners and genuine spare parts.', 'https://epson.co.ke'],
  ['HP', 'hp', 'HP LaserJet and ink printers, original toner cartridges and replacement parts.', 'https://www.hp.com'],
  ['Canon', 'canon', 'Canon PIXMA ink tank printers, imageCLASS lasers, scanners and ink.', 'https://www.canon-ea.com'],
  ['Brother', 'brother', 'Brother laser and ink tank printers, toner, drums and accessories.', 'https://www.brother.co.ke'],
  ['Samsung', 'samsung', 'Samsung laser printer toner and spare parts.', null],
  ['Kyocera', 'kyocera', 'Kyocera ECOSYS printers and long-life toner kits.', 'https://www.kyoceradocumentsolutions.eu'],
  ['Xerox', 'xerox', 'Xerox printers, toner and drum cartridges.', null],
  ['Ricoh', 'ricoh', 'Ricoh office printers, toner and maintenance parts.', null],
  ['Konica Minolta', 'konica-minolta', 'Konica Minolta bizhub toner and imaging units.', null],
  ['Pantum', 'pantum', 'Pantum affordable mono laser printers and toner.', null],
]

// [name, slug, parentSlug, description, image]
export const categories = [
  ['Printers', 'printers', null, 'Ink tank, laser, dot matrix and photo printers for home, office and business in Kenya.', 'printer-inktank-black'],
  ['Ink Tank Printers', 'ink-tank', 'printers', 'High-yield ink tank printers with refillable bottles for the lowest cost per page.', 'printer-inktank-white'],
  ['Laser Printers', 'laser', 'printers', 'Fast, reliable mono and colour laser printers for offices.', 'printer-laser-white'],
  ['Dot Matrix Printers', 'dot-matrix', 'printers', 'Impact printers for invoices, multipart forms and receipts.', 'printer-dot-matrix'],
  ['Photo Printers', 'photo-printers', 'printers', 'Six-colour photo printers for studios and creatives.', 'printer-photo'],
  ['Ink & Toner', 'ink-toner', null, 'Original ink bottles, toner cartridges and drum units.', 'ink-bottle-set'],
  ['Ink', 'ink', 'ink-toner', 'Original refill ink bottles for ink tank printers.', 'ink-bottle-set'],
  ['Toner', 'toner', 'ink-toner', 'Toner cartridges and drum units for laser printers.', 'toner-black'],
  ['Spare Parts', 'spare-parts', null, 'Genuine and compatible printer spare parts: rollers, printheads, fusers and maintenance kits.', 'printhead'],
  ['Printheads', 'printheads', 'spare-parts', 'Replacement printheads for ink tank printers.', 'printhead'],
  ['Pickup Rollers', 'pickup-rollers', 'spare-parts', 'Pickup, separation and feed rollers to fix paper jams and misfeeds.', 'pickup-roller'],
  ['Fuser Units', 'fuser-units', 'spare-parts', 'Fuser assemblies for laser printers.', 'fuser-unit'],
  ['Maintenance Kits', 'maintenance-kits', 'spare-parts', 'Waste ink pads, maintenance boxes and service kits.', 'maintenance-kit'],
  ['Paper Feed Parts', 'paper-feed-parts', 'spare-parts', 'Feed rollers, trays and paper path parts.', 'pickup-roller'],
  ['Scanners', 'scanners', null, 'Flatbed and document scanners for home and office.', 'scanner'],
  ['Paper & Media', 'paper-media', null, 'Copy paper, photo paper and printing media.', 'paper-ream'],
  ['Accessories', 'accessories', null, 'Cables and printer accessories.', 'usb-cable'],
  ['Cables', 'cables', 'accessories', 'USB printer cables.', 'usb-cable'],
]

// [brandSlug, name, modelNumber]
export const printerModels = [
  ['epson', 'Epson EcoTank L3250', 'L3250'],
  ['epson', 'Epson EcoTank L3210', 'L3210'],
  ['epson', 'Epson EcoTank L3150', 'L3150'],
  ['epson', 'Epson EcoTank L3110', 'L3110'],
  ['epson', 'Epson EcoTank L5290', 'L5290'],
  ['epson', 'Epson L805', 'L805'],
  ['epson', 'Epson LQ-310', 'LQ-310'],
  ['hp', 'HP LaserJet Pro M404dn', 'M404dn'],
  ['hp', 'HP LaserJet Pro M404dw', 'M404dw'],
  ['hp', 'HP LaserJet Pro M405dn', 'M405dn'],
  ['hp', 'HP LaserJet Pro M203dw', 'M203dw'],
  ['hp', 'HP LaserJet Pro MFP M227fdw', 'M227fdw'],
  ['canon', 'Canon PIXMA G3420', 'G3420'],
  ['canon', 'Canon PIXMA G2410', 'G2410'],
  ['canon', 'Canon PIXMA G3411', 'G3411'],
  ['brother', 'Brother HL-L2350DW', 'HL-L2350DW'],
  ['brother', 'Brother DCP-L2540DW', 'DCP-L2540DW'],
  ['brother', 'Brother DCP-T420W', 'DCP-T420W'],
  ['brother', 'Brother DCP-T520W', 'DCP-T520W'],
  ['kyocera', 'Kyocera ECOSYS P2040dn', 'P2040dn'],
  ['pantum', 'Pantum P2500W', 'P2500W'],
]

const printerSpecs = (o) =>
  [
    ['Print Technology', o.tech],
    ['Functions', o.functions],
    ['Print Speed', o.speed],
    ['Resolution', o.resolution],
    ['Connectivity', o.connectivity],
    ['Wi-Fi', o.wifi ? 'Yes' : 'No'],
    ['USB', o.usb ?? 'Hi-Speed USB 2.0'],
    ['Duplex', o.duplex ?? 'Manual'],
    ['Paper Size', o.paper ?? 'A4, A5, A6, B5, Letter, Legal, envelopes'],
    ['Monthly Duty Cycle', o.duty],
    ['Dimensions', o.dimensions],
    ['Weight', o.weight],
    ['Warranty', o.warranty ?? '1 year'],
  ].filter(([, v]) => v)

const partSpecs = (o) =>
  [
    ['Part Number', o.partNumber],
    ['OEM Number', o.oem],
    ['Part Type', o.partType],
    ['Condition', o.condition ?? 'New'],
    ['Compatible Brands', o.brands],
    ['Yield', o.yield],
    ['Volume', o.volume],
    ['Warranty', o.warranty ?? '3 months'],
  ].filter(([, v]) => v)

// Product fields: sku, name, slug, brand, category, type, price, compare, stock, flags,
// short, description, specs, features, included, compat (model numbers), printerModel,
// images, variants, partNumber
export const products = [
  // ---------------------------------------------------------------- Printers
  {
    sku: 'EPS-L3250', name: 'Epson EcoTank L3250 All-in-One Wi-Fi Printer', slug: 'epson-ecotank-l3250-all-in-one-printer',
    brand: 'epson', category: 'ink-tank', type: 'printer', price: 32999, compare: 35000, stock: 18,
    flags: ['featured', 'bestseller'], printerModel: 'L3250', images: ['printer-inktank-black', 'ink-bottle-set'],
    short: 'Print • Scan • Copy • Wi-Fi',
    description: 'The Epson EcoTank L3250 is a compact, wireless all-in-one ink tank printer built for ultra-low printing costs. Its refillable tanks print up to 4,500 black and 7,500 colour pages from the included bottles, and Wi-Fi Direct lets you print straight from phones and laptops without a router. Ideal for homes, students and small offices that print often.',
    specs: printerSpecs({ tech: 'Heat-Free Micro Piezo inkjet (ink tank)', functions: 'Print, scan, copy', speed: 'Up to 10 ipm black / 5 ipm colour (ISO)', resolution: '5760 × 1440 dpi', connectivity: 'Wi-Fi, Wi-Fi Direct, USB', wifi: true, duty: 'Up to 3,000 pages', dimensions: '375 × 347 × 179 mm', weight: '3.9 kg', warranty: '1 year or 30,000 pages' }),
    features: ['Ultra-low cost printing with refillable ink tanks', 'Wireless and Wi-Fi Direct printing', 'Epson Smart Panel app for mobile printing and scanning', 'Spill-free, error-free bottle refilling', 'Borderless photo printing up to 4R'],
    included: ['Epson EcoTank L3250 printer', '4 × Epson 003 ink bottles (BK, C, M, Y)', 'Power cable', 'Setup guide'],
  },
  {
    sku: 'EPS-L3210', name: 'Epson EcoTank L3210 All-in-One Printer', slug: 'epson-ecotank-l3210-all-in-one-printer',
    brand: 'epson', category: 'ink-tank', type: 'printer', price: 27499, stock: 22, flags: ['bestseller'],
    printerModel: 'L3210', images: ['printer-inktank-white'], short: 'Print • Scan • Copy • USB',
    description: 'A dependable USB ink tank all-in-one for high-volume home and office printing at a very low cost per page. Integrated tanks with bottle keys make refilling clean and simple.',
    specs: printerSpecs({ tech: 'Heat-Free Micro Piezo inkjet (ink tank)', functions: 'Print, scan, copy', speed: 'Up to 10 ipm black / 5 ipm colour (ISO)', resolution: '5760 × 1440 dpi', connectivity: 'USB', wifi: false, duty: 'Up to 3,000 pages', dimensions: '375 × 347 × 179 mm', weight: '3.9 kg' }),
    features: ['Very low cost per page', 'Compact integrated tank design', 'Borderless printing up to 4R'],
    included: ['Printer', '4 × Epson 003 ink bottles', 'USB cable', 'Power cable'],
  },
  {
    sku: 'EPS-L5290', name: 'Epson EcoTank L5290 Wi-Fi All-in-One with ADF', slug: 'epson-ecotank-l5290-wifi-all-in-one-adf',
    brand: 'epson', category: 'ink-tank', type: 'printer', price: 45999, compare: 49500, stock: 7, flags: ['featured', 'sale'],
    printerModel: 'L5290', images: ['printer-inktank-grey'], short: 'Print • Scan • Copy • Fax • ADF • Ethernet',
    description: 'Built for busy small offices: a 30-sheet automatic document feeder, fax, Ethernet and Wi-Fi, all with EcoTank running costs.',
    specs: printerSpecs({ tech: 'Heat-Free Micro Piezo inkjet (ink tank)', functions: 'Print, scan, copy, fax', speed: 'Up to 10 ipm black / 5 ipm colour (ISO)', resolution: '5760 × 1440 dpi', connectivity: 'Wi-Fi, Wi-Fi Direct, Ethernet, USB', wifi: true, duty: 'Up to 3,000 pages', dimensions: '375 × 347 × 231 mm', weight: '5.0 kg' }),
    features: ['30-sheet ADF for multipage scanning and copying', 'Ethernet and Wi-Fi networking', 'Fax with PC-fax support'],
    included: ['Printer', '4 × Epson 003 ink bottles', 'Power cable', 'Phone cable'],
  },
  {
    sku: 'EPS-L805', name: 'Epson L805 Wi-Fi Photo Ink Tank Printer', slug: 'epson-l805-wifi-photo-printer',
    brand: 'epson', category: 'photo-printers', type: 'printer', price: 41500, stock: 4, flags: [],
    printerModel: 'L805', images: ['printer-photo'], short: '6-colour photo • Wi-Fi • CD/DVD printing',
    description: 'Six-colour photo printing with lab-quality results, Wi-Fi and direct CD/DVD printing. A favourite of photo studios and creatives across Kenya.',
    specs: printerSpecs({ tech: '6-colour inkjet (ink tank)', functions: 'Print', speed: 'Approx. 12 sec per 10 × 15 cm photo', resolution: '5760 × 1440 dpi', connectivity: 'Wi-Fi, USB', wifi: true, duty: null, dimensions: '542 × 289 × 169 mm', weight: '6.0 kg' }),
    features: ['Six-colour ink system for vivid photos', 'Print directly onto CD/DVDs', 'Borderless photos up to A4'],
    included: ['Printer', '6 × ink bottles', 'CD/DVD tray', 'Power cable'],
  },
  {
    sku: 'CAN-G3420', name: 'Canon PIXMA G3420 Wi-Fi Ink Tank All-in-One', slug: 'canon-pixma-g3420-wifi-ink-tank',
    brand: 'canon', category: 'ink-tank', type: 'printer', price: 25999, compare: 27999, stock: 15, flags: ['featured'],
    printerModel: 'G3420', images: ['printer-inktank-black'], short: 'Print • Scan • Copy • Wi-Fi',
    description: 'Canon\'s wireless refillable ink tank printer with high page yields of up to 6,000 black and 7,000 colour pages per set of bottles.',
    specs: printerSpecs({ tech: 'Inkjet (refillable ink tank)', functions: 'Print, scan, copy', speed: 'Up to 9.1 ipm black / 5.0 ipm colour', resolution: '4800 × 1200 dpi', connectivity: 'Wi-Fi, USB', wifi: true, duty: null, dimensions: '445 × 330 × 163 mm', weight: '6.3 kg' }),
    features: ['High page yield GI-490 inks', 'Wireless printing from Canon PRINT app', 'Borderless photo printing'],
    included: ['Printer', 'GI-490 ink bottles (BK, C, M, Y)', 'Print head set', 'Power cable'],
  },
  {
    sku: 'CAN-G2410', name: 'Canon PIXMA G2410 Ink Tank All-in-One', slug: 'canon-pixma-g2410-ink-tank',
    brand: 'canon', category: 'ink-tank', type: 'printer', price: 19999, stock: 12, flags: ['new'],
    printerModel: 'G2410', images: ['printer-inktank-white'], short: 'Print • Scan • Copy • USB',
    description: 'An affordable refillable ink tank all-in-one for homes and students who want low running costs.',
    specs: printerSpecs({ tech: 'Inkjet (refillable ink tank)', functions: 'Print, scan, copy', speed: 'Up to 8.8 ipm black / 5.0 ipm colour', resolution: '4800 × 1200 dpi', connectivity: 'USB', wifi: false, duty: null, dimensions: '445 × 330 × 163 mm', weight: '5.8 kg' }),
    features: ['Low running costs', 'Integrated front-facing tanks', 'Borderless photos up to 4R'],
    included: ['Printer', 'GI-490 ink bottles', 'Print head set', 'Power cable'],
  },
  {
    sku: 'HP-M404DN', name: 'HP LaserJet Pro M404dn Mono Laser Printer', slug: 'hp-laserjet-pro-m404dn',
    brand: 'hp', category: 'laser', type: 'printer', price: 52999, stock: 9, flags: ['featured', 'bestseller'],
    printerModel: 'M404dn', images: ['printer-laser-white', 'toner-black'], short: '38 ppm • Duplex • Ethernet',
    description: 'Fast, secure mono laser printing for busy offices. Automatic two-sided printing, Gigabit Ethernet and HP Wolf security keep work moving.',
    specs: printerSpecs({ tech: 'Monochrome laser', functions: 'Print', speed: 'Up to 38 ppm (A4)', resolution: '1200 × 1200 dpi', connectivity: 'Gigabit Ethernet, USB', wifi: false, duplex: 'Automatic', duty: 'Up to 80,000 pages', dimensions: '381 × 357 × 216 mm', weight: '8.56 kg' }),
    features: ['Automatic duplex printing', 'First page out in as fast as 6.3 seconds', '250-sheet input tray plus 100-sheet multipurpose tray'],
    included: ['Printer', 'HP 59A starter toner cartridge', 'Power cable', 'Documentation'],
  },
  {
    sku: 'HP-M203DW', name: 'HP LaserJet Pro M203dw Wireless Mono Laser', slug: 'hp-laserjet-pro-m203dw',
    brand: 'hp', category: 'laser', type: 'printer', price: 34500, stock: 0, flags: [],
    printerModel: 'M203dw', images: ['printer-laser-dark'], short: '28 ppm • Duplex • Wi-Fi',
    description: 'Compact wireless laser printer with automatic duplex for small offices.',
    specs: printerSpecs({ tech: 'Monochrome laser', functions: 'Print', speed: 'Up to 28 ppm (A4)', resolution: '1200 × 1200 dpi', connectivity: 'Wi-Fi, Ethernet, USB', wifi: true, duplex: 'Automatic', duty: 'Up to 30,000 pages', dimensions: '360 × 264 × 224 mm', weight: '5.6 kg' }),
    features: ['Wireless and mobile printing', 'Automatic duplex'],
    included: ['Printer', 'HP 30A starter toner', 'Power cable'],
  },
  {
    sku: 'BRO-HLL2350DW', name: 'Brother HL-L2350DW Wireless Mono Laser Printer', slug: 'brother-hl-l2350dw-wireless-laser',
    brand: 'brother', category: 'laser', type: 'printer', price: 28999, compare: 31000, stock: 11, flags: ['sale'],
    printerModel: 'HL-L2350DW', images: ['printer-laser-dark'], short: '30 ppm • Duplex • Wi-Fi',
    description: 'Reliable compact mono laser with automatic two-sided printing and wireless connectivity. Uses separate toner and drum for lower running costs.',
    specs: printerSpecs({ tech: 'Monochrome laser', functions: 'Print', speed: 'Up to 30 ppm (A4)', resolution: '2400 × 600 dpi', connectivity: 'Wi-Fi, Wi-Fi Direct, USB', wifi: true, duplex: 'Automatic', duty: 'Up to 15,000 pages', dimensions: '356 × 360 × 183 mm', weight: '7.0 kg' }),
    features: ['Separate toner and drum', 'Automatic duplex', 'Mobile printing'],
    included: ['Printer', 'Inbox toner', 'Drum unit', 'Power cable'],
  },
  {
    sku: 'BRO-DCPT420W', name: 'Brother DCP-T420W Wi-Fi Ink Tank All-in-One', slug: 'brother-dcp-t420w-ink-tank',
    brand: 'brother', category: 'ink-tank', type: 'printer', price: 26500, stock: 6, flags: ['new'],
    printerModel: 'DCP-T420W', images: ['printer-inktank-grey'], short: 'Print • Scan • Copy • Wi-Fi',
    description: 'Wireless refill ink tank printer with high-yield BTD60BK and BT5000 inks.',
    specs: printerSpecs({ tech: 'Inkjet (refill ink tank)', functions: 'Print, scan, copy', speed: 'Up to 16 ipm mono / 9 ipm colour', resolution: '6000 × 1200 dpi', connectivity: 'Wi-Fi, USB', wifi: true, duty: '2,500 pages', dimensions: '435 × 359 × 159 mm', weight: '6.6 kg' }),
    features: ['Up to 7,500 mono pages per bottle', 'Wireless printing'],
    included: ['Printer', 'Starter ink bottles', 'Power cable'],
  },
  {
    sku: 'PAN-P2500W', name: 'Pantum P2500W Wireless Mono Laser Printer', slug: 'pantum-p2500w-wireless-laser',
    brand: 'pantum', category: 'laser', type: 'printer', price: 15999, stock: 25, flags: ['new', 'featured'],
    printerModel: 'P2500W', images: ['printer-laser-white'], short: '22 ppm • Wi-Fi • Compact',
    description: 'An affordable compact wireless laser printer, ideal for homes, cyber cafés and small offices.',
    specs: printerSpecs({ tech: 'Monochrome laser', functions: 'Print', speed: 'Up to 22 ppm (A4)', resolution: '1200 × 1200 dpi', connectivity: 'Wi-Fi, USB', wifi: true, duty: 'Up to 15,000 pages', dimensions: '337 × 220 × 178 mm', weight: '4.75 kg' }),
    features: ['Very affordable laser printing', 'Wireless printing'],
    included: ['Printer', 'Starter toner (1,600 pages)', 'Power cable'],
  },
  {
    sku: 'KYO-P2040DN', name: 'Kyocera ECOSYS P2040dn Mono Laser Printer', slug: 'kyocera-ecosys-p2040dn',
    brand: 'kyocera', category: 'laser', type: 'printer', price: 48000, stock: 3, flags: [],
    printerModel: 'P2040dn', images: ['printer-laser-white'], short: '40 ppm • Duplex • Long-life drum',
    description: 'Kyocera\'s long-life components deliver some of the lowest running costs in its class.',
    specs: printerSpecs({ tech: 'Monochrome laser', functions: 'Print', speed: 'Up to 40 ppm (A4)', resolution: '1200 × 1200 dpi', connectivity: 'Gigabit Ethernet, USB', wifi: false, duplex: 'Automatic', duty: 'Up to 50,000 pages', dimensions: '375 × 393 × 272 mm', weight: '11.5 kg', warranty: '1 year' }),
    features: ['Long-life drum', 'Automatic duplex'],
    included: ['Printer', 'Starter toner', 'Power cable'],
  },
  {
    sku: 'EPS-LQ310', name: 'Epson LQ-310 24-pin Dot Matrix Printer', slug: 'epson-lq-310-dot-matrix',
    brand: 'epson', category: 'dot-matrix', type: 'printer', price: 36999, stock: 5, flags: [],
    printerModel: 'LQ-310', images: ['printer-dot-matrix'], short: '24-pin • Multipart forms',
    description: 'A rugged 24-pin dot matrix printer for invoices, delivery notes and multipart forms.',
    specs: printerSpecs({ tech: '24-pin impact dot matrix', functions: 'Print', speed: 'Up to 416 cps', resolution: '360 × 180 dpi', connectivity: 'USB, parallel', wifi: false, paper: 'Continuous, cut sheet, multipart (1 + 3 copies)', duty: null, dimensions: '348 × 275 × 159 mm', weight: '4.1 kg' }),
    features: ['Prints original + 3 copies', 'Low running cost ribbons'],
    included: ['Printer', 'Ribbon cartridge', 'Power cable'],
  },

  // ------------------------------------------------------------- Ink & toner
  {
    sku: 'EPS-003', name: 'Epson 003 Original Ink Bottle (65 ml)', slug: 'epson-003-original-ink-bottle',
    brand: 'epson', category: 'ink', type: 'ink_toner', price: 1150, stock: 0, flags: ['bestseller', 'featured'],
    images: ['ink-bottle-set'], partNumber: '003', short: 'Black 4,500 pages • Colour 7,500 pages',
    compat: ['L3250', 'L3210', 'L3150', 'L3110', 'L5290'],
    description: 'Genuine Epson 003 ink bottles with keyed nozzles for spill-free refilling of EcoTank L-series printers.',
    specs: partSpecs({ partNumber: '003', partType: 'Ink bottle', brands: 'Epson', volume: '65 ml', yield: '4,500 pages (black), 7,500 pages (colour)' }),
    features: ['Keyed bottle prevents filling the wrong tank', 'Genuine Epson ink protects your printhead'],
    included: ['1 × 65 ml ink bottle'],
    variants: [
      ['Black', 'EPS-003-BK', 1150, 40, 'ink-bottle-black', { Colour: 'Black' }],
      ['Cyan', 'EPS-003-C', 1150, 30, 'ink-bottle-cyan', { Colour: 'Cyan' }],
      ['Magenta', 'EPS-003-M', 1150, 28, 'ink-bottle-magenta', { Colour: 'Magenta' }],
      ['Yellow', 'EPS-003-Y', 1150, 3, 'ink-bottle-yellow', { Colour: 'Yellow' }],
    ],
  },
  {
    sku: 'CAN-GI490', name: 'Canon GI-490 Original Ink Bottle', slug: 'canon-gi-490-ink-bottle',
    brand: 'canon', category: 'ink', type: 'ink_toner', price: 1100, stock: 0, flags: [],
    images: ['ink-bottle-set'], partNumber: 'GI-490', short: 'Black 6,000 pages • Colour 7,000 pages',
    compat: ['G3420', 'G2410', 'G3411'],
    description: 'Genuine Canon GI-490 refill ink for PIXMA G-series ink tank printers.',
    specs: partSpecs({ partNumber: 'GI-490', partType: 'Ink bottle', brands: 'Canon', volume: '135 ml (black), 70 ml (colour)', yield: '6,000 pages (black), 7,000 pages (colour)' }),
    features: ['Pigment black for sharp text', 'Dye colours for vibrant photos'],
    included: ['1 × ink bottle'],
    variants: [
      ['Black (135 ml)', 'CAN-GI490-BK', 1200, 20, 'ink-bottle-black', { Colour: 'Black' }],
      ['Cyan (70 ml)', 'CAN-GI490-C', 1100, 14, 'ink-bottle-cyan', { Colour: 'Cyan' }],
      ['Magenta (70 ml)', 'CAN-GI490-M', 1100, 14, 'ink-bottle-magenta', { Colour: 'Magenta' }],
      ['Yellow (70 ml)', 'CAN-GI490-Y', 1100, 12, 'ink-bottle-yellow', { Colour: 'Yellow' }],
    ],
  },
  {
    sku: 'HP-CF259A', name: 'HP 59A Black Original LaserJet Toner Cartridge (CF259A)', slug: 'hp-59a-black-toner-cf259a',
    brand: 'hp', category: 'toner', type: 'ink_toner', price: 14500, compare: 15800, stock: 14, flags: ['sale'],
    images: ['toner-black'], partNumber: 'CF259A', short: 'Approx. 3,000 pages • Black',
    compat: ['M404dn', 'M404dw', 'M405dn'],
    description: 'Original HP 59A toner for consistent, sharp mono printing on LaserJet Pro M404 and M405 printers.',
    specs: partSpecs({ partNumber: 'CF259A', oem: 'HP 59A', partType: 'Toner cartridge', brands: 'HP', yield: 'Approx. 3,000 pages (ISO)' }),
    features: ['JetIntelligence page-maximising technology', 'Anti-fraud protection'],
    included: ['1 × toner cartridge'],
  },
  {
    sku: 'HP-CF230A', name: 'HP 30A Black Original LaserJet Toner Cartridge (CF230A)', slug: 'hp-30a-black-toner-cf230a',
    brand: 'hp', category: 'toner', type: 'ink_toner', price: 9999, stock: 10, flags: [],
    images: ['toner-black'], partNumber: 'CF230A', short: 'Approx. 1,600 pages • Black',
    compat: ['M203dw', 'M227fdw'],
    description: 'Original HP 30A toner for LaserJet Pro M203 and MFP M227 printers.',
    specs: partSpecs({ partNumber: 'CF230A', oem: 'HP 30A', partType: 'Toner cartridge', brands: 'HP', yield: 'Approx. 1,600 pages (ISO)' }),
    features: ['Original HP toner'], included: ['1 × toner cartridge'],
  },
  {
    sku: 'BRO-TN2420', name: 'Brother TN-2420 High Yield Toner Cartridge', slug: 'brother-tn-2420-toner',
    brand: 'brother', category: 'toner', type: 'ink_toner', price: 9800, stock: 16, flags: [],
    images: ['toner-blue-band'], partNumber: 'TN-2420', short: 'Approx. 3,000 pages • Black',
    compat: ['HL-L2350DW', 'DCP-L2540DW'],
    description: 'High-yield genuine Brother toner for HL-L2350DW and DCP-L2540DW printers.',
    specs: partSpecs({ partNumber: 'TN-2420', partType: 'Toner cartridge', brands: 'Brother', yield: 'Approx. 3,000 pages (ISO)' }),
    features: ['Genuine Brother toner'], included: ['1 × toner cartridge'],
  },
  {
    sku: 'BRO-DR2405', name: 'Brother DR-2405 Drum Unit', slug: 'brother-dr-2405-drum-unit',
    brand: 'brother', category: 'toner', type: 'spare_part', price: 8500, stock: 5, flags: [],
    images: ['drum-unit'], partNumber: 'DR-2405', short: 'Approx. 12,000 pages',
    compat: ['HL-L2350DW', 'DCP-L2540DW'],
    description: 'Replacement drum unit. Replace when the printer reports "Replace Drum" or prints show repeating marks.',
    specs: partSpecs({ partNumber: 'DR-2405', partType: 'Drum unit', brands: 'Brother', yield: 'Approx. 12,000 pages' }),
    features: ['Genuine Brother drum'], included: ['1 × drum unit'],
  },
  {
    sku: 'BRO-BTD60BK', name: 'Brother BTD60BK Black Ink Bottle', slug: 'brother-btd60bk-black-ink',
    brand: 'brother', category: 'ink', type: 'ink_toner', price: 1450, stock: 20, flags: [],
    images: ['ink-bottle-black'], partNumber: 'BTD60BK', short: 'Approx. 6,500 pages • Black',
    compat: ['DCP-T420W', 'DCP-T520W'],
    description: 'Genuine Brother pigment black ink bottle for DCP-T series ink tank printers.',
    specs: partSpecs({ partNumber: 'BTD60BK', partType: 'Ink bottle', brands: 'Brother', volume: '108 ml', yield: 'Approx. 6,500 pages' }),
    features: ['Pigment ink for crisp text'], included: ['1 × 108 ml ink bottle'],
  },
  {
    sku: 'PAN-PC211EV', name: 'Pantum PC-211EV Toner Cartridge', slug: 'pantum-pc-211ev-toner',
    brand: 'pantum', category: 'toner', type: 'ink_toner', price: 4800, stock: 30, flags: ['bestseller'],
    images: ['toner-light'], partNumber: 'PC-211EV', short: 'Approx. 1,600 pages • Black',
    compat: ['P2500W'],
    description: 'Original Pantum toner for P2500 series printers.',
    specs: partSpecs({ partNumber: 'PC-211EV', partType: 'Toner cartridge', brands: 'Pantum', yield: 'Approx. 1,600 pages' }),
    features: ['Easy drop-in replacement'], included: ['1 × toner cartridge'],
  },
  {
    sku: 'KYO-TK1160', name: 'Kyocera TK-1160 Toner Kit', slug: 'kyocera-tk-1160-toner',
    brand: 'kyocera', category: 'toner', type: 'ink_toner', price: 11500, stock: 8, flags: [],
    images: ['toner-black'], partNumber: 'TK-1160', short: 'Approx. 7,200 pages • Black',
    compat: ['P2040dn'],
    description: 'Genuine Kyocera toner kit for ECOSYS P2040dn and P2040dw.',
    specs: partSpecs({ partNumber: 'TK-1160', partType: 'Toner kit', brands: 'Kyocera', yield: 'Approx. 7,200 pages' }),
    features: ['Long-life toner'], included: ['1 × toner kit', 'Waste toner bag'],
  },

  // ------------------------------------------------------------- Spare parts
  {
    sku: 'SP-RM2-5452', name: 'HP LaserJet Pro M404 / M405 Pickup Roller', slug: 'hp-laserjet-m404-m405-pickup-roller',
    brand: 'hp', category: 'pickup-rollers', type: 'spare_part', price: 2500, stock: 24, flags: ['bestseller', 'featured'],
    images: ['pickup-roller'], partNumber: 'RM2-5452-000', short: 'Fixes misfeeds and paper jams from Tray 2',
    compat: ['M404dn', 'M404dw', 'M405dn'],
    description: 'Replacement Tray 2 pickup roller for HP LaserJet Pro M404 and M405 printers. A worn pickup roller is the most common cause of "paper jam" and "load paper" errors when paper is in the tray.',
    specs: partSpecs({ partNumber: 'RM2-5452-000', partType: 'Pickup roller', brands: 'HP', condition: 'New (compatible)' }),
    features: ['Restores reliable paper pickup', 'Tool-free installation in minutes'],
    included: ['1 × pickup roller assembly'],
  },
  {
    sku: 'SP-RM2-5399', name: 'HP LaserJet Pro M404 / M405 Fuser Unit (220V)', slug: 'hp-laserjet-m404-m405-fuser-unit-220v',
    brand: 'hp', category: 'fuser-units', type: 'spare_part', price: 18500, stock: 3, flags: [],
    images: ['fuser-unit'], partNumber: 'RM2-5399-000', short: '220V • Fixes smudged or unfused prints',
    compat: ['M404dn', 'M404dw', 'M405dn'],
    description: 'Fuser assembly for HP LaserJet Pro M404/M405. Replace when prints smudge, toner rubs off or the printer reports a fuser error (50.x).',
    specs: partSpecs({ partNumber: 'RM2-5399-000', partType: 'Fuser unit', brands: 'HP', condition: 'New (compatible)', warranty: '3 months' }),
    features: ['220V version for Kenya'], included: ['1 × fuser assembly'],
  },
  {
    sku: 'SP-FA04010', name: 'Epson L3110 / L3150 / L3210 / L3250 Printhead', slug: 'epson-l3110-l3150-l3250-printhead',
    brand: 'epson', category: 'printheads', type: 'spare_part', price: 9500, compare: 10500, stock: 6, flags: ['featured'],
    images: ['printhead'], partNumber: 'FA04010', short: 'Fixes missing colours and banding',
    compat: ['L3110', 'L3150', 'L3210', 'L3250'],
    description: 'Replacement printhead for Epson EcoTank L3110, L3150, L3210 and L3250. Fit when head cleaning no longer restores missing colours or lines.',
    specs: partSpecs({ partNumber: 'FA04010', oem: 'FA04000', partType: 'Printhead', brands: 'Epson', condition: 'New (original)' }),
    features: ['Original Epson printhead'], included: ['1 × printhead'],
  },
  {
    sku: 'SP-EPS-PADKIT', name: 'Epson L-Series Waste Ink Pad Maintenance Kit', slug: 'epson-l-series-waste-ink-pad-kit',
    brand: 'epson', category: 'maintenance-kits', type: 'spare_part', price: 1200, stock: 35, flags: [],
    images: ['maintenance-kit'], partNumber: 'EPS-PAD-L3', short: 'For "service required" / red-light errors',
    compat: ['L3110', 'L3150', 'L3210', 'L3250', 'L5290'],
    description: 'Replacement waste ink absorber pads for Epson L-series printers. Pair with an ink pad counter reset when the printer shows "Service Required".',
    specs: partSpecs({ partNumber: 'EPS-PAD-L3', partType: 'Waste ink pads', brands: 'Epson', condition: 'New (compatible)' }),
    features: ['High-absorption pads'], included: ['Waste ink pad set'],
  },
  {
    sku: 'SP-CAN-GFEED', name: 'Canon PIXMA G-Series Paper Feed Roller', slug: 'canon-pixma-g-series-paper-feed-roller',
    brand: 'canon', category: 'paper-feed-parts', type: 'spare_part', price: 1800, stock: 9, flags: ['new'],
    images: ['pickup-roller'], partNumber: 'QM7-xxxx', short: 'Rear tray paper feed roller',
    compat: ['G3420', 'G2410', 'G3411'],
    description: 'Paper feed roller for Canon PIXMA G2410, G3411 and G3420. Fixes paper not feeding from the rear tray.',
    specs: partSpecs({ partNumber: 'QM7-xxxx', partType: 'Paper feed roller', brands: 'Canon', condition: 'New (compatible)' }),
    features: ['Restores reliable feeding'], included: ['1 × feed roller'],
  },

  // ------------------------------------------------------------- Scanners
  {
    sku: 'EPS-V39II', name: 'Epson Perfection V39 II Flatbed Photo Scanner', slug: 'epson-perfection-v39-ii-scanner',
    brand: 'epson', category: 'scanners', type: 'scanner', price: 18999, stock: 5, flags: [],
    images: ['scanner'], short: '4800 dpi • USB powered',
    description: 'Slim USB-powered flatbed scanner for documents and photos with scan-to-cloud.',
    specs: [['Scanner Type', 'Flatbed'], ['Optical Resolution', '4800 × 4800 dpi'], ['Interface', 'USB 2.0 (bus powered)'], ['Max Scan Size', 'A4'], ['Warranty', '1 year']],
    features: ['Scan to cloud', 'Removable lid for books'], included: ['Scanner', 'USB cable'],
  },
  {
    sku: 'CAN-LIDE300', name: 'Canon CanoScan LiDE 300 Flatbed Scanner', slug: 'canon-canoscan-lide-300',
    brand: 'canon', category: 'scanners', type: 'scanner', price: 11500, compare: 12500, stock: 7, flags: ['sale'],
    images: ['scanner'], short: '2400 dpi • USB powered',
    description: 'Compact, affordable flatbed scanner for everyday documents and photos.',
    specs: [['Scanner Type', 'Flatbed'], ['Optical Resolution', '2400 × 2400 dpi'], ['Interface', 'USB 2.0 (bus powered)'], ['Max Scan Size', 'A4'], ['Warranty', '1 year']],
    features: ['One-touch scan buttons'], included: ['Scanner', 'USB cable'],
  },

  // ------------------------------------------------------------- Paper & accessories
  {
    sku: 'PAP-COPY', name: 'Premium Copy Paper Ream (500 sheets)', slug: 'premium-copy-paper-ream',
    brand: null, category: 'paper-media', type: 'paper', price: 750, stock: 0, flags: ['bestseller'],
    images: ['paper-ream', 'paper-ream-a3'], short: 'A4 / A3 • 80 – 100 gsm',
    description: 'Bright white multipurpose copy paper for laser and inkjet printers and copiers.',
    specs: [['Sheets', '500 per ream'], ['Brightness', 'CIE 161'], ['Use', 'Laser, inkjet, copier']],
    features: ['Jam-free performance'], included: ['1 ream (500 sheets)'],
    variants: [
      ['A4 80gsm', 'PAP-A4-80', 750, 120, 'paper-ream', { Size: 'A4', Weight: '80gsm' }],
      ['A4 100gsm', 'PAP-A4-100', 1150, 40, 'paper-ream', { Size: 'A4', Weight: '100gsm' }],
      ['A3 80gsm', 'PAP-A3-80', 1650, 25, 'paper-ream-a3', { Size: 'A3', Weight: '80gsm' }],
    ],
  },
  {
    sku: 'EPS-GLOSSY-A4', name: 'Epson Premium Glossy Photo Paper A4 (20 sheets)', slug: 'epson-premium-glossy-photo-paper-a4',
    brand: 'epson', category: 'paper-media', type: 'paper', price: 1200, stock: 18, flags: [],
    images: ['photo-paper'], short: '255 gsm • Instant dry',
    description: 'Instant-dry glossy photo paper for vivid, long-lasting prints.',
    specs: [['Size', 'A4'], ['Weight', '255 gsm'], ['Finish', 'Glossy'], ['Sheets', '20']],
    features: ['Instant dry'], included: ['20 sheets'],
  },
  {
    sku: 'ACC-USB-AB', name: 'USB 2.0 Printer Cable (A to B)', slug: 'usb-printer-cable-a-to-b',
    brand: null, category: 'cables', type: 'accessory', price: 450, stock: 0, flags: [],
    images: ['usb-cable'], short: 'Shielded • 1.5 m / 3 m',
    description: 'Shielded USB 2.0 A-to-B cable that connects most printers and scanners to a computer.',
    specs: [['Connector', 'USB-A male to USB-B male'], ['Standard', 'USB 2.0'], ['Shielding', 'Foil + braid']],
    features: ['Gold-plated connectors'], included: ['1 × cable'],
    variants: [
      ['1.5 m', 'ACC-USB-AB-15', 450, 60, 'usb-cable', { Length: '1.5 m' }],
      ['3 m', 'ACC-USB-AB-30', 650, 30, 'usb-cable', { Length: '3 m' }],
    ],
  },
]

export const reviews = [
  // [productSku, reviewerIndex, rating, title, comment]
  ['EPS-L3250', 0, 5, 'Excellent value', 'Set up in 10 minutes and the ink lasts forever. Printing from my phone over Wi-Fi works perfectly.'],
  ['EPS-L3250', 1, 4, 'Great printer for home office', 'Prints are sharp and the running cost is very low. Scanning is a bit slow but fine.'],
  ['EPS-L3250', 2, 5, 'Fast delivery in Nairobi', 'Ordered in the morning, delivered the same day. Genuine product with warranty.'],
  ['HP-M404DN', 0, 5, 'Workhorse', 'Fast, quiet and duplex works great. Our office prints 2,000 pages a month on it.'],
  ['SP-RM2-5452', 1, 5, 'Fixed our paper jams', 'Our M404 kept saying paper jam. Replaced this roller and it works like new.'],
  ['EPS-003', 2, 5, 'Genuine ink', 'Original Epson bottles, good price.'],
  ['PAN-P2500W', 1, 4, 'Good budget laser', 'Great for school work. Wi-Fi setup took a few tries.'],
]
