// Builds supabase/seed.sql from scripts/seed/catalog.mjs.
// Usage: node scripts/seed/generate.mjs
//
// The seed is for local development only. It creates demo users:
//   admin@ciss.local / Admin12345!     (super_admin)
//   customer@ciss.local / Customer12345! (customer)
import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { brands, categories, printerModels, products, reviews } from './catalog.mjs'

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..')

const q = (v) => {
  if (v === null || v === undefined) return 'null'
  if (typeof v === 'number') return String(v)
  if (typeof v === 'boolean') return v ? 'true' : 'false'
  return `'${String(v).replace(/'/g, "''")}'`
}
const arr = (list) => `array[${list.map(q).join(', ')}]::text[]`
const json = (v) => `${q(JSON.stringify(v))}::jsonb`
const img = (name) => `/images/products/${name}.svg`

const out = []
out.push('-- Generated by scripts/seed/generate.mjs. Do not edit by hand.')
out.push('-- Local development data only.\n')
out.push('begin;\n')

// Demo users ----------------------------------------------------------------
const users = [
  ['00000000-0000-4000-8000-000000000001', 'admin@ciss.local', 'Admin12345!', 'CISS Admin', 'super_admin'],
  ['00000000-0000-4000-8000-000000000002', 'customer@ciss.local', 'Customer12345!', 'Wanjiku Kamau', 'customer'],
  ['00000000-0000-4000-8000-000000000003', 'brian@ciss.local', 'Customer12345!', 'Brian Otieno', 'customer'],
  ['00000000-0000-4000-8000-000000000004', 'amina@ciss.local', 'Customer12345!', 'Amina Hassan', 'customer'],
]
for (const [id, email, password, name] of users) {
  out.push(`insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, email_change,
  email_change_token_new, recovery_token)
values ('00000000-0000-0000-0000-000000000000', ${q(id)}, 'authenticated', 'authenticated', ${q(email)},
  extensions.crypt(${q(password)}, extensions.gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}', ${json({ full_name: name })}, now(), now(), '', '', '', '')
on conflict (id) do nothing;`)
  out.push(`insert into auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
values (gen_random_uuid(), ${q(id)}, ${q(id)}, ${json({ sub: id, email, email_verified: true })}, 'email', now(), now(), now())
on conflict do nothing;`)
}
for (const [id, , , , role] of users) {
  out.push(`update public.profiles set role = ${q(role)} where id = ${q(id)};`)
}
out.push('')

// Brands --------------------------------------------------------------------
out.push('insert into public.brands (name, slug, description, website, sort_order) values')
out.push(
  brands
    .map(([name, slug, description, website], i) => `  (${q(name)}, ${q(slug)}, ${q(description)}, ${q(website)}, ${i * 10})`)
    .join(',\n') + ';\n',
)

// Categories (parents first) ---------------------------------------------------
for (const [i, [name, slug, parent, description, image]] of categories.entries()) {
  out.push(`insert into public.categories (name, slug, parent_id, description, image_url, sort_order, seo_title, seo_description)
values (${q(name)}, ${q(slug)}, ${parent ? `(select id from public.categories where slug = ${q(parent)})` : 'null'},
  ${q(description)}, ${q(img(image))}, ${i * 10}, ${q(`${name} in Kenya | CISS Solutions`)}, ${q(description)});`)
}
out.push('')

// Printer models ---------------------------------------------------------------
out.push('insert into public.printer_models (brand_id, name, model_number, slug) values')
out.push(
  printerModels
    .map(
      ([brand, name, model]) =>
        `  ((select id from public.brands where slug = ${q(brand)}), ${q(name)}, ${q(model)}, ${q(name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, ''))})`,
    )
    .join(',\n') + ';\n',
)

// Products ------------------------------------------------------------------------
for (const p of products) {
  const flags = new Set(p.flags ?? [])
  const specs = (p.specs ?? []).map(([label, value]) => ({ label, value }))
  const price = p.variants ? Math.min(...p.variants.map((v) => v[2])) : p.price
  out.push(`insert into public.products (name, slug, sku, brand_id, category_id, printer_model_id, product_type,
  short_description, description, part_number, specifications, features, whats_included, warranty, price,
  compare_at_price, stock_quantity, low_stock_threshold, status, is_featured, is_bestseller, is_new, is_on_sale,
  seo_title, seo_description)
values (${q(p.name)}, ${q(p.slug)}, ${q(p.sku)},
  ${p.brand ? `(select id from public.brands where slug = ${q(p.brand)})` : 'null'},
  (select id from public.categories where slug = ${q(p.category)}),
  ${p.printerModel ? `(select id from public.printer_models where model_number = ${q(p.printerModel)})` : 'null'},
  ${q(p.type)}, ${q(p.short)}, ${q(p.description)}, ${q(p.partNumber ?? null)}, ${json(specs)},
  ${arr(p.features ?? [])}, ${arr(p.included ?? [])}, ${q(specs.find((s) => s.label === 'Warranty')?.value ?? null)},
  ${price}, ${q(p.compare ?? null)}, ${p.variants ? 0 : p.stock}, ${p.type === 'printer' ? 3 : 5}, 'active',
  ${flags.has('featured')}, ${flags.has('bestseller')}, ${flags.has('new')}, ${flags.has('sale')},
  ${q(`${p.name} Price in Kenya | CISS Solutions`)}, ${q(`Buy ${p.name} in Kenya. ${p.short}. Genuine products, nationwide delivery and M-Pesa payment.`)});`)

  out.push(`insert into public.product_costs (product_id, cost_price)
values ((select id from public.products where sku = ${q(p.sku)}), ${Math.round(price * 0.78)});`)

  for (const [i, image] of (p.images ?? []).entries()) {
    out.push(`insert into public.product_images (product_id, url, alt_text, sort_order, is_primary)
values ((select id from public.products where sku = ${q(p.sku)}), ${q(img(image))}, ${q(i === 0 ? p.name : `${p.name} – view ${i + 1}`)}, ${i}, ${i === 0});`)
  }

  for (const [i, [name, sku, vPrice, stock, image, options]] of (p.variants ?? []).entries()) {
    out.push(`insert into public.product_variants (product_id, name, sku, option_values, price, stock_quantity, image_url, sort_order)
values ((select id from public.products where sku = ${q(p.sku)}), ${q(name)}, ${q(sku)}, ${json(options)}, ${vPrice}, ${stock}, ${q(img(image))}, ${i});`)
  }

  for (const model of p.compat ?? []) {
    out.push(`insert into public.product_compatibility (product_id, printer_model_id)
values ((select id from public.products where sku = ${q(p.sku)}), (select id from public.printer_models where model_number = ${q(model)}));`)
  }
  out.push('')
}

// Reviews (approved) ---------------------------------------------------------------
for (const [sku, reviewer, rating, title, comment] of reviews) {
  const [id, , , name] = users[reviewer + 1]
  out.push(`insert into public.reviews (product_id, user_id, author_name, rating, title, comment, status, is_verified_purchase)
values ((select id from public.products where sku = ${q(sku)}), ${q(id)}, ${q(name.split(' ')[0])}, ${rating}, ${q(title)}, ${q(comment)}, 'approved', true);`)
}
out.push('')

// Homepage hero slides ---------------------------------------------------------------
out.push(`insert into public.homepage_banners (eyebrow, title, highlight, subtitle, image_url, image_alt, cta_text, cta_url,
  secondary_cta_text, secondary_cta_url, featured_product_id, sort_order) values
  ('In stock', 'Epson EcoTank L3250', null,
   'Refillable ink tanks for a low cost per page. Prints, scans and copies over Wi-Fi.',
   '/images/products/printer-inktank-black.svg', 'Epson EcoTank ink tank printer', 'View printer', '/p/epson-ecotank-l3250-all-in-one-printer', 'All ink tank printers', '/c/printers/ink-tank',
   (select id from public.products where sku = 'EPS-L3250'), 10),
  ('For the office', 'Mono laser printers', null,
   'Duplex, networked laser printers from HP, Brother, Kyocera and Pantum, with toner to match.',
   '/images/products/printer-laser-white.svg', 'Mono laser printer', 'Shop laser printers', '/c/printers/laser', 'Find toner', '/c/ink-toner/toner',
   (select id from public.products where sku = 'HP-M404DN'), 20),
  ('Spare parts', 'Rollers, printheads and fusers', null,
   'Matched to your printer model. Not sure what you need? Send us the model and the problem.',
   '/images/products/printhead.svg', 'Printer printhead spare part', 'Find a part', '/parts-finder', 'Ask a technician', '/support/part-request',
   (select id from public.products where sku = 'SP-FA04010'), 30);
`)

// Coupons -------------------------------------------------------------------------------
out.push(`insert into public.coupons (code, description, discount_type, value, minimum_order, maximum_discount, usage_limit, per_customer_limit)
values ('CISS10', '10% off orders over KSh 5,000', 'percentage', 10, 5000, 5000, 1000, 1),
       ('INK500', 'KSh 500 off ink and toner over KSh 3,000', 'fixed', 500, 3000, null, null, 3);
update public.coupons set applicable_category_ids = array[(select id from public.categories where slug = 'ink-toner')]
 where code = 'INK500';
`)

// Business details for local development -----------------------------------------------------------
out.push(`update public.settings set value = value || ${json({
  phone: '+254 700 000 000',
  whatsapp: '254700000000',
  email: 'sales@cisssolutions.co.ke',
  address: 'Nairobi CBD, Kenya',
})} where key = 'business';`)

out.push('\ncommit;')
writeFileSync(join(root, 'supabase', 'seed.sql'), out.join('\n') + '\n')
console.log(`Wrote supabase/seed.sql (${products.length} products)`)
